# emoji_map.py
# Maps Discord custom emoji names → team names exactly as they appear in the Google Sheet.
#
# HOW TO FIND AN EMOJI'S NAME:
#   In Discord, type a backslash before the emoji: \:YourEmoji:
#   Discord will show you the full text like <:MilwaukeeBucks:1234567890>
#   The name is the part between the colons → "MilwaukeeBucks"
#
# IMPORTANT: The team name on the right must match EXACTLY what's in row 1
#            of that team's section in your Google Sheet (including capitalisation).
#
# FORMAT:
#   "EmojiName": "Team Name In Sheet",

EMOJI_TEAM_MAP = {
    # ── Add your teams below ──────────────────────────────────────────────────
    # "MilwaukeeBucks":           "Milwaukee Bucks",
    # "MiamiHeat":                "Miami Heat",
    # "TorontoRaptors":           "Toronto Raptors",
    # "WashingtonWizards":        "Washington Wizards",
    # "OrlandoMagic":             "Orlando Magic",
    # "NewOrleansHornets":        "New Orleans Hornets",
    # "NewYorkLiberty":           "New York Liberty",
    # "WashingtonStateCougars":   "Washington State Cougars",
    # "NorthwesternWildcats":     "Northwestern Wildcats",
    # "UCSantaCruzBananaSlugs":   "UC Santa Cruz Banana Slugs",
    # ─────────────────────────────────────────────────────────────────────────
    "San_Antonio_Spurs": "San Antonio Spurs",
    "Spurs": "San Antonio Spurs",
    "Spurs~1": "San Antonio Spurs",
    "Milwaukee_Bucks": "Milwaukee Bucks",
    "Warriors": "Golden State Warriors",
    "Pacers": "Indiana Pacers",
    "Lakers": "Los Angeles Lakers",
    "Heat": "Miami Heat",
    "Heat2": "Miami Heat",
    "Raptors": "Toronto Raptors",
    "Wizards": "Washington Wizards",
    "Magic": "Orlando Magic",
    "Hornets": "New Orleans Hornets",
    "PSR": "Providence Steamrollers",
    "Cavs": "Cleveland Cavaliers",
    "Celtics": "Boston Celtics",
    "Clippers": "Los Angeles Clippers",
    "CornellBigRed": "Cornell Big Red",
    "Duke": "Duke Blue Devils",
    "Gonzaga": "Gonzaga Bulldogs",
    "Kentucky": "Kentucky Wildcats",
    "Kansas": "Kansas Jayhawks",
    "Northwestern": "Northwestern Wildcats",
    "Sonics": "Seattle SuperSonics",
    "OKC": "Oklahoma City Thunder",
    "UNC": "North Carolina Tar Heels",
    "Pelicans": "New Orleans Pelicans",
    "Nuggets": "Denver Nuggets",
    "Jazz": "Utah Jazz",
    "MichiganState": "Michigan State Spartans",
    "LSU": "LSU Tigers",
    "UCLA": "UCLA Bruins",
    "Uconn": "UConn Huskies",
    "TCU": "TCU Horned Frogs",
    "Iowa": "Iowa Hawkeyes",
    "Ohio": "Ohio State Buckeyes",
    "Purdue": "Purdue Boilermakers",
    "Marquette": "Marquette Golden Eagles",
    "Louisville": "Louisville Cardinals",
    "Washington_State_Cougars": "Washington State Cougars",
    "Orl2": "Orlando Magic",
    "UCSantaCruzBananaSlugs": "UCSC Banana Slugs",
    "Minn": "Minnesota Timberwolves",
    "Titans": "Tennessee Titans",
    "Browns": "Cleveland Browns",
    "Pacers": "Indiana Pacers",
    "Nets": "Brooklyn Nets",
    "Bulls": "Chicago Bulls",
    "Grizzlies": "Memphis Grizzlies",
    "Rockets": "Houston Rockets",
    "Kings": "Sacramento Kings",
    "76ers": "Philadelphia 76ers",
    "Mavericks": "Dallas Mavericks",
    "Bucks": "Milwaukee Bucks",
    "Knicks": "New York Knicks",
    "Suns": "Phoenix Suns",
    "WashingtonHuskies": "Washington Huskies",
    "WashingtonHuskies~1": "Washington Huskies",
    "Piston": "Detroit Pistons",
    "Syracuse": "Syracuse Orange",
    "Hoosiers": "Indiana Hoosiers",
    "Bobcats": "Charlotte Bobcats",
    "MichiganWolverines": "Michigan Wolverines",
    "DrakeBulldogs": "Drake Bulldogs",
    "OKST": "Oklahoma State Cowboys",
    "CreightonBulljays": "Creighton Bluejays",
    "CalPoly:": "Cal Poly Mustangs",
    "CCSU:": "Ctr. Connecticut Blue Devils",
    "SIUE:": "SIU-Edwardsville Cougars",
    "TOR": "Toronto Huskies",
    "arkansasrazorbacks": "Arkansas Razorbacks",
    "Celtics~1": "Boston Celtics",
    "heat2": "Miami Heat",          # :heat2: in lotto
    "Northwestern~1": "Northwestern Wildcats",
    "IOWncaa": "Iowa Hawkeyes",
    "NOH": "New Orleans Hornets",
    "Clippers~1": "Los Angeles Clippers",
    "MichiganWolverines~1": "Michigan Wolverines",
    "TOR2~1": "Toronto Huskies",
    "TulaneGreenWave~1": "Tulane Green Wave",
    "ravens": "Baltimore Ravens",
    "UConn": "UConn Huskies",
    "Knicks~1": "New York Knicks",
    "76ers_Old": "Philadelphia 76ers",
    "MIN~7": "Minnesota Timberwolves",
    "pistons~2": "Detroit Pistons",
    "0Clemson~2": "Clemson Tigers",
    "0Clemson": "Clemson Tigers",
}
