# emoji_map.py
# Maps Discord custom emoji names → team names exactly as they appear in the Google Sheet.
#
# HOW TO FIND AN EMOJI'S NAME:
#   In Discord, type a backslash before the emoji: \:YourEmoji:
#   Discord will show you the full text like <:MilwaukeeBucks:1234567890>
#   The name is the part between the colons → "MilwaukeeBucks"
#
# IMPORTANT: The team name on the right must match EXACTLY what's in row 1
#            of that team's section in your Google Sheet (including capitalisation).
#
# FORMAT:
#   "EmojiName": "Team Name In Sheet",

EMOJI_TEAM_MAP = {
    # ── Add your teams below
    "San_Antonio_Spurs": "San Antonio Spurs",
    "SAS": "San Antonio Spurs",
    "Spurs": "San Antonio Spurs",
    "Spurs~1": "San Antonio Spurs",
    "Milwaukee_Bucks": "Milwaukee Bucks",
    "Warriors": "Golden State Warriors",
    "Pacers": "Indiana Pacers",
    "Lakers": "Los Angeles Lakers",
    "Heat": "Miami Heat",
    "Heat2": "Miami Heat",
    "MIA": "Miami Heat",
    "Raptors": "Toronto Raptors",
    "Wizards": "Washington Wizards",
    "Magic": "Orlando Magic",
    "Hornets": "New Orleans Hornets",
    "PSR": "Providence Steamrollers",
    "Cavs": "Cleveland Cavaliers",
    "Celtics": "Boston Celtics",
    "Clippers": "Los Angeles Clippers",
    "CornellBigRed": "Cornell Big Red",
    "Duke": "Duke Blue Devils",
    "Gonzaga": "Gonzaga Bulldogs",
    "Kentucky": "Kentucky Wildcats",
    "Kansas": "Kansas Jayhawks",
    "Northwestern": "Northwestern Wildcats",
    "Sonics": "Seattle SuperSonics",
    "OKC": "Oklahoma City Thunder",
    "UNC": "North Carolina Tar Heels",
    "Pelicans": "New Orleans Pelicans",
    "pelicans": "New Orleans Pelicans",
    "Nuggets": "Denver Nuggets",
    "nuggets": "Denver Nuggets",
    "Jazz": "Utah Jazz",
    "MichiganState": "Michigan State Spartans",
    "LSU": "LSU Tigers",
    "UCLA": "UCLA Bruins",
    "Uconn": "UConn Huskies",
    "TCU": "TCU Horned Frogs",
    "Iowa": "Iowa Hawkeyes",
    "Ohio": "Ohio State Buckeyes",
    "Purdue": "Purdue Boilermakers",
    "Marquette": "Marquette Golden Eagles",
    "Louisville": "Louisville Cardinals",
    "Washington_State_Cougars": "Washington State Cougars",
    "Orl2": "Orlando Magic",
    "UCSantaCruzBananaSlugs": "UCSC Banana Slugs",
    "Minn": "Minnesota Timberwolves",
    "MIN": "Minnesota Timberwolves",
    "Titans": "Tennessee Titans",
    "Browns": "Cleveland Browns",
    "Pacers": "Indiana Pacers",
    "Nets": "Brooklyn Nets",
    "Bulls": "Chicago Bulls",
    "Grizzlies": "Memphis Grizzlies",
    "MEM": "Memphis Grizzlies",
    "Rockets": "Houston Rockets",
    "Kings": "Sacramento Kings",
    "76ers": "Philadelphia 76ers",
    "Mavericks": "Dallas Mavericks",
    "mavs": "Dallas Mavericks",
    "Bucks": "Milwaukee Bucks",
    "MIL2": "Milwaukee Bucks",
    "Knicks": "New York Knicks",
    "Suns": "Phoenix Suns",
    "WashingtonHuskies": "Washington Huskies",
    "huskies": "Washington Huskies",
    "WashingtonHuskies~1": "Washington Huskies",
    "Piston": "Detroit Pistons",
    "pistons": "Detroit Pistons",
    "Syracuse": "Syracuse Orange",
    "Hoosiers": "Indiana Hoosiers",
    "Bobcats": "Charlotte Bobcats",
    "MichiganWolverines": "Michigan Wolverines",
    "DrakeBulldogs": "Drake Bulldogs",
    "OKST": "Oklahoma State Cowboys",
    "CreightonBulljays": "Creighton Bluejays",
    "CreightonBluejays": "Creighton Bluejays",
    "CalPoly:": "Cal Poly Mustangs",
    "CCSU:": "Ctr. Connecticut Blue Devils",
    "SIUE:": "SIU-Edwardsville Cougars",
    "arkansasrazorbacks": "Arkansas Razorbacks",
    "Celtics~1": "Boston Celtics",
    "heat": "Miami Heat",
    "heat2": "Miami Heat",        
    "Northwestern~1": "Northwestern Wildcats",
    "IOWncaa": "Iowa Hawkeyes",
    "NOH": "New Orleans Hornets",
    "NOH~1": "New Orleans Hornets",
    ":NOH~2:": "New Orleans Hornets",
    "Clippers~1": "Los Angeles Clippers",
    "MichiganWolverines~1": "Michigan Wolverines",
    "TOR2~1": "Toronto Huskies",
    "TOR2": "Toronto Huskies",
    "TulaneGreenWave~1": "Tulane Green Wave",
    "TulaneGreenWave": "Tulane Green Wave",
    "ravens": "Baltimore Ravens",
    "UConn": "UConn Huskies",
    "Knicks~1": "New York Knicks",
    "76ers_Old": "Philadelphia 76ers",
    "MIN~7": "Minnesota Timberwolves",
    "pistons~2": "Detroit Pistons",
    "0Clemson~2": "Clemson Tigers",
    "0Clemson": "Clemson Tigers",
    "ClemsonTigers": "Clemson Tigers",
    "SAS~5": "San Antonio Spurs",
    "titans": "Tennessee Titans",
    "nuggets~3": "Denver Nuggets",
    "ucf_knights": "UCF Knights",
    "miami": "Miami Hurricanes",
    "Maine_Black_Bears": "Maine Black Bears",
    "trailblazers": "Portland Trail Blazers",
    "rockets": "Houston Rockets",
    "VAN": "Vancouver Grizzlies",
    "Celtics2": "Boston Celtics",
    "CIN": "Cincinnati Royals",
    "BAL": "Baltimore Bullets",
    "SDR": "San Diego Rockets",
    "VIR": "Virginia Squires",
    "NYK": "New York Knicks",
    "CLE": "Cleveland Cavaliers",
    "NPC": "Newport",              
    "ORL": "Orlando Magic",
    "ORL2": "Orlando Magic",
    "IND": "Indiana Pacers",
    "DAL": "Dallas Mavericks",
    "POR": "Portland Trail Blazers",
    "PHI": "Philadelphia 76ers",
    "SAC": "Sacramento Kings",
    "CHI": "Chicago Bulls",
    "NOP": "New Orleans Pelicans",
    "UTA": "Utah Jazz",
    "MIL": "Milwaukee Bucks",
    "HOU": "Houston Rockets",
    "ATL": "Atlanta Hawks",
    "SMU": "SMU Mustangs",
    "CHA": "Charlotte Hornets",
    "PHO": "Phoenix Suns",
    "LAL": "Los Angeles Lakers",
    "BKN": "Brooklyn Nets",
    "BOS": "Boston Celtics",
    "DET": "Detroit Pistons",
    "DEN": "Denver Nuggets",
    "DUKE": "Duke Blue Devils",
    "GSW": "Golden State Warriors",
    "NW": "Northwestern Wildcats",
    "NJN": "New Jersey Nets",
    "TOR": "Toronto Raptors",
    "TOR~4": "Toronto Raptors",
}

# Unicode (built-in Discord) emojis → team names.
# Add flag/country emojis here.
UNICODE_EMOJI_MAP = {
    "🇫🇷": "France",
    "🇺🇸": "USA",
}
