PLAYER_POSITIONS = {
    # From your provided table
    "Michael Jordan": "SG/PG",
    "LeBron James": "PF/SF",
    "Shaquille O'Neal": "C",
    "Stephen Curry": "PG/SG",
    "Kevin Garnett": "PF/C",
    "Larry Bird": "PF/SF",
    "Magic Johnson": "PG/SF/PF",
    "Kareem Abdul-Jabbar": "C",
    "Hakeem Olajuwon": "C",
    "Kevin Durant": "PF/SF",
    "Kobe Bryant": "SG",
    "Jerry West": "SG/PG",
    "Tim Duncan": "PF/C",
    "Nikola Jokic": "C",
    "Kawhi Leonard": "SF/SG",
    "Shai Gilgeous-Alexander": "SG/PG",
    "Dwyane Wade": "SG/PG",
    "David Robinson": "C",
    "Steve Nash": "PG",
    "Chris Paul": "PG",
    "Tracy McGrady": "SG/SF/PG",
    "Oscar Robertson": "PG",
    "Bill Walton": "C",
    "Giannis Antetokounmpo": "PF/C",
    "Wilt Chamberlain": "C",
    "Anthony Davis": "PF/C",
    "Joel Embiid": "C",
    "Julius Erving": "SF/PF",
    "Bill Russell": "C/PF",
    "James Harden": "PG/SG",
    "Karl Malone": "PF/C",
    "Dirk Nowitzki": "PF",
    
    # Additional players from your examples
    "Gilbert Arenas": "PG",
    "Eddie Jones": "SG",
    "Clyde Drexler": "SG",
    "Chris Bosh": "PF/C",
    "Reggie Lewis": "SG",
    "Dave Cowens": "C/PF",
    "Walter Davis": "SG/SF",
    "Victor Wembanyama": "C/PF",
    "Brent Barry": "SG",
    "Luka Doncic": "PG/SG",
    "Paul George": "SF/SG",
    "Jaren Jackson Jr.": "PF/C",
    "Kevin Garnett": "PF/C",
    "Oscar Robertson": "PG",
    "Magic Johnson": "PG",
    "Julius Erving": "SF",
    "Rasheed Wallace": "PF/C",
    "Shaquille O'Neal": "C",
    "Dwight Howard": "C",
    "Phil Chenier": "SG",
    "Victor Oladipo": "SG",
    "Larry Bird": "SF/PF",
    "Bill Russell": "C",
    "Tyrese Maxey": "PG/SG",
    "Reggie Miller": "SG",
    "Kevin Durant": "SF/PF",
    "Marc Gasol": "C",
    "Dennis Rodman": "PF",
    "Dennis Johnson": "PG/SG",
    "Charles Barkley": "PF",
    
    # Add more players as needed
}