def _normalize(s: str) -> str:
    return "".join(ch for ch in s.lower() if ch.isalnum())


# Common nicknames the bot recognizes automatically in segment lines, without
# a GM having to declare them in a team's `Nick=Full Name` legend. A team's
# own declared nicknames always take priority over this list, and an entry
# here only resolves if the player it points to is actually on that team's
# roster (see parser.py).
#
# Matching ignores case, spaces, periods, hyphens, and apostrophes -- but the
# nickname still has to be typed as a single word in a rotation line (no
# spaces), e.g. "DrJ", not "Dr J".
_RAW_NICKNAMES = {
    "DrJ": "Julius Erving",
    "Spida": "Donovan Mitchell",
    "MJ": "Michael Jordan",
    "AirJordan": "Michael Jordan",
    "AI": "Allen Iverson",
    "TheAnswer": "Allen Iverson",
    "KD": "Kevin Durant",
    "Slim Reaper": "Kevin Durant",
    "SlimReaper": "Kevin Durant",
    "CP3": "Chris Paul",
    "TMac": "Tracy McGrady",
    "Melo": "Carmelo Anthony",
    "Mamba": "Kobe Bryant",
    "BlackMamba": "Kobe Bryant",
    "Bron": "LeBron James",
    "KingJames": "LeBron James",
    "Chef": "Stephen Curry",
    "ChefCurry": "Stephen Curry",
    "Steph": "Stephen Curry",
    "Zo": "Alonzo Mourning",
    "Sheed": "Rasheed Wallace",
    "Boogie": "DeMarcus Cousins",
    "Flash": "Dwyane Wade",
    "DWade": "Dwyane Wade",
    "Vinsanity": "Vince Carter",
    "HalfMan": "Vince Carter",
    "Mailman": "Karl Malone",
    "Admiral": "David Robinson",
    "Glove": "Gary Payton",
    "GP": "Gary Payton",
    "Worm": "Dennis Rodman",
    "Pistol": "Pete Maravich",
    "Diesel": "Shaquille O'Neal",
    "Shaq": "Shaquille O'Neal",
    "AgentZero": "Gilbert Arenas",
    "Dream": "Hakeem Olajuwon",
    "HakeemTheDream": "Hakeem Olajuwon",
    "Iceman": "George Gervin",
    "Pearl": "Earl Monroe",
    "Nique": "Dominique Wilkins",
    "HumanHighlightFilm": "Dominique Wilkins",
    "GreekFreak": "Giannis Antetokounmpo",
    "Giannis": "Giannis Antetokounmpo",
    "Klaw": "Kawhi Leonard",
    "Kawhi": "Kawhi Leonard",
    "Beard": "James Harden",
    "Joker": "Nikola Jokic",
    "Jokic": "Nikola Jokic",
    "Zion": "Zion Williamson",
    "Luka": "Luka Doncic",
    "Doncic": "Luka Doncic",
    "Wemby": "Victor Wembanyama",
    "SGA": "Shai Gilgeous-Alexander",
    "Dame": "Damian Lillard",
    "DameTime": "Damian Lillard",
    "Book": "Devin Booker",
    "PG13": "Paul George",
    "Embiid": "Joel Embiid",
    "Kyrie": "Kyrie Irving",
    "Klay": "Klay Thompson",
    "Dray": "Draymond Green",
    "Brodie": "Russell Westbrook",
    "TheTruth": "Paul Pierce",
    "BigFundamental": "Tim Duncan",
    "Fundamental": "Tim Duncan",
    "TheGlide": "Clyde Drexler",
    "Clyde": "Clyde Drexler",
    "Skip": "Rafer Alston",
    "TheMailman": "Karl Malone",
    "PennyHardaway": "Penny Hardaway",
    "AD": "Anthony Davis",
    "TheBrow": "Anthony Davis",
    "Manu": "Manu Ginobili",
    "Dirk": "Dirk Nowitzki",
    "TheBigGerman": "Dirk Nowitzki",
    "Kobe": "Kobe Bryant",
    "Magic": "Magic Johnson",
    "Bird": "Larry Bird",
    "LarryLegend": "Larry Bird",
    "TheMayor": "Damian Lillard",
    "Chocolate Thunder": "Darryl Dawkins",
    "ChocolateThunder": "Darryl Dawkins",
    "Zeke": "Isiah Thomas",
    "Sir Charles": "Charles Barkley",
    "SirCharles": "Charles Barkley",
    "Chuck": "Charles Barkley",
    "Rondo": "Rajon Rondo",
    "CB4": "Chris Bosh",
    "Melo Anthony": "Carmelo Anthony",
    "Trae": "Trae Young",
    "IceTrae": "Trae Young",
    "Hali": "Tyrese Haliburton",
    "BigGameJames": "James Worthy",
    "TheProcess": "Joel Embiid",
    "Rip": "Richard Hamilton",
    "TheChief": "Robert Parish",
    "Chief": "Robert Parish",
    "Kareem": "Kareem Abdul-Jabbar",
    "Gallo": "Danilo Gallinari",
    "Silk": "Jamaal Wilkes",
    "Deke": "Dikembe Mutombo",
    "Ant": "Anthony Edwards",
    "AntMan": "Anthony Edwards",
    "BaldMamba": "Alex Caruso",
    "Dice": "Antonio McDyess",
    "JT": "Jayson Tatum",
    "SpicyP": "Pascal Siakam",
    "AR15": "Austin Reaves",
    "MPJ": "Michael Porter Jr.",
    "ClydeFrazier": "Walt Frazier",
    "SweetLou": "Lou Hudson",
    "KLove": "Kevin Love",
    "Superman": "Dwight Howard",
    "Skywalker": "David Thompson",
    "BigShotRob": "Robert Horry",
    "BigE": "Elvin Hayes",
}

KNOWN_NICKNAMES = {_normalize(k): v for k, v in _RAW_NICKNAMES.items()}


def resolve_known_nickname(token: str) -> str | None:
    return KNOWN_NICKNAMES.get(_normalize(token))
