# Maps old/alternative names (lowercased) → current Win Sheet name.
# Keys are what might appear in a lotto entry after @ parsing.
# Values are the canonical Win Sheet name (case preserved).
# Add entries here whenever someone changes their name.
DRAFTER_ALIASES = {
    "lebron d james r":     "Dogboy",
    "lucario":              "Element",
    "ahoppppppp":           "ahop",
    "imdoomed":             "Bony",
    "matisse thybulle":     "Matisse",
    "#ihatepra #lesspra":   "Qrganic",
    "#ihatepra":            "Qrganic",
    "ashrith's dirt":       "Boneless",
    "jsoapz":               "Soapz",
    "homer":                "lml",
    "3v 🪽 #freebanny":     "r3con",
    "3v 🪽":                "r3con",
    "[afk] fade to black":  "Mk",
    "solid31":              "TelluricSolid31",
    "momomoney#bruhpack":         "Momo",
    "momomoney":                  "Momo",
    "momomoney #shoutoutgooby":   "Momo",
    "gethigher77":                "Datboi",
    "goobynky":                   "Gooby",
    "ceokelvin":                  "Ceo",

    "lucario baseketball":        "Element",
    "r3v 🪽 #freebanny":          "r3con",
    "r3v 🪽":                     "r3con",
    "r3":                         "r3con",
    "blocked by bam":             "Blocked By Bam",
    "asoapz 💫":                  "ASoapz",
    "nate ⁶𓅓":                   "Nate",
    "cam 💫":                     "Cam",
    ".thunderly":                 "Thunderly",
    "udon_lover":                 "udon",
    "tissy":                      "Matisse",
    "ackbar":                     "Admiral Ackbar",
    "telluricsolid":              "TelluricSolid31",
    "mattise":                    "Matisse",
    "itsyaboi":                   "itsyaboi.idk",
    # ── ATD 52–58 ────────────────────────────────────────────────────────────────
    "[afk] snipez":                             "Snipez",
    "snoop dawg ⚜":                             "Snoop Dawg",
    "caliph ♬":                                 "caliph",
    "aura cruz 🇲🇽":                            "Cruz",
    "exceptionalrichboychucky":                 "Chucky",
    "old jester account":                       "Jester",
    "من، پو، تنها بالای بقیه ایستاده":          "Po",
    "shadow":                                   "Shadows",
    "solid":                                    "TelluricSolid31",
    "pizardsbrodie":                            "Pizards",
    "pizard":                                   "Pizards",
    "#nomoreagendas":                           "Pepe",
    "bad mario gamer":                          "Villian2Death",
    "villain2death":                            "Villian2Death",
    "serj":                                     "AJ",
    "13enny":                                   "Benny",
    "freaknd glazer":                           "Dogboy",
    "easy":                                     "Easybruh",
    "assaultedбyadebayo":                       "Qrganic",
    "assaultedbyadebayo":                       "Qrganic",
}
