CHAMPIONS = {
    1:  {"w": ["Load"],                                               "ru": ["josh"]},
    2:  {"w": ["JSoapz"],                                             "ru": ["13enny"]},
    3:  {"w": ["Bony"],                                               "ru": ["hooper_hoes"]},
    4:  {"w": ["josh"],                                               "ru": ["JSoapz"]},
    5:  {"w": ["JSoapz"],                                             "ru": ["Bony"]},
    6:  {"w": ["Bony"],                                               "ru": ["hooper_hoes"]},
    7:  {"w": ["Storm"],                                              "ru": ["dallama"]},
    8:  {"w": ["JSoapz"],                                             "ru": ["hooper_hoes"]},
    # 9 = NFL, 10 = Cancelled
    11: {"w": ["JSoapz"],                                             "ru": ["bean"]},
    12: {"w": ["JSoapz"],                                             "ru": ["betches"]},
    13: {"w": ["bean", "myst imo"],                                   "ru": ["tinymouse"]},
    14: {"w": ["JoeJoe/Rick/Michael"],                                "ru": []},
    15: {"w": ["Bony"],                                               "ru": ["hooper_hoes"]},
    16: {"w": ["JSoapz"],                                             "ru": ["pacer"]},
    17: {"w": ["dallama"],                                            "ru": ["hooper_hoes"]},
    18: {"w": ["Ceo"],                                                "ru": ["Cruz"]},
    # 19 = Cancelled, 20 = Cancelled
    21: {"w": ["dallama"],                                            "ru": ["htb"]},
    # 22 = Cancelled, 23 = Cancelled
    24: {"w": ["JSoapz"],                                             "ru": ["r3"]},
    25: {"w": [],                                                     "ru": ["r3"]},
    26: {"w": ["JSoapz", "chicagofan"],                               "ru": ["myst imo", "dallama"]},
    27: {"w": ["sam"],                                                "ru": ["Snipez"]},
    28: {"w": ["Unlimited"],                                          "ru": ["Bony"]},
    29: {"w": ["made"],                                               "ru": ["unknown-user", "myst imo"]},
    # 30 = NFL
    31: {"w": ["CCarp"],                                              "ru": ["unknown-user"]},
    32: {"w": [],                                                     "ru": ["young slime"]},
    33: {"w": ["Bony"],                                               "ru": ["JSoapz", "CCarp"]},
    34: {"w": ["sorslab"],                                            "ru": []},
    35: {"w": ["Silveryo"],                                           "ru": ["sorslab", "unknown-user"]},
    36: {"w": ["Silveryo"],                                           "ru": ["Ceo"]},
    37: {"w": ["The Jester", "Unlimited"],                            "ru": ["AJ", "JSoapz"]},
    38: {"w": ["Cruz"],                                               "ru": ["unknown-user", "dallama"]},
    39: {"w": ["AJ", "exceptionalrichboychucky"],                     "ru": ["Benzo", "Load"]},
    40: {"w": ["JSoapz", "CCarp"],                                    "ru": ["Udon_Lover", "collins"]},
    41: {"w": ["Bony"],                                               "ru": ["CCarp", "Load", "jan"]},
    42: {"w": ["Snipez"],                                             "ru": ["CCarp"]},
    43: {"w": ["Bony", "Cruz", "valter", "dallama"],                  "ru": ["Benzo"]},
    44: {"w": ["Hayden", "JSoapz"],                                   "ru": ["Benzo"]},
    45: {"w": ["Nate", "JSoapz", "shadow"],                           "ru": ["Ferra", "Hilol", "bobby", "collins"]},
    46: {"w": ["Kay", "r3", "Crispy"],                                          "ru": ["Benzo"]},
    47: {"w": ["Matisse Thybulle", "jakit"],                          "ru": ["AJ", "unknown-user"]},
    # 48 = Football
    49: {"w": [],                                                     "ru": ["zenon", "Ferra"]},
    50: {"w": ["Silveryo"],                                           "ru": ["Mk"]},
    51: {"w": ["ozzy"],                                               "ru": ["Bony"]},
    52: {"w": ["Mk"],                                                 "ru": ["Francis", "Hilol"]},
    53: {"w": ["JSoapz", "Qrganic"],                                  "ru": ["Deuce (Maye Szn)"]},
    54: {"w": ["Ceo"],                                                "ru": ["Deleted User"]},
    55: {"w": ["JSoapz"],                                             "ru": ["Admiral Ackbar"]},
    56: {"w": ["JSoapz", "bear"],                                     "ru": ["r3", "goldi"]},
    57: {"w": ["JSoapz", "sorslab"],                                  "ru": ["Francis"]},
    58: {"w": ["Silveryo"],                                           "ru": ["Deleted User"]},
    59: {"w": ["r3", "cayden"],                                       "ru": ["self proclaimed d1 glazer", "Nate"]},
    60: {"w": ["Kay", "Thunderly"],                                   "ru": ["Admiral Ackbar"]},
    61: {"w": ["Qrganic"],                                            "ru": ["JSoapz"]},
    62: {"w": ["Benzo"],                                              "ru": []},
    63: {"w": ["Cam"],                                                "ru": ["CCarp"]},
    64: {"w": ["Silveryo", "JoeJoe/Rick/Michael"],                    "ru": ["chicagofan", "Gooby"]},
    65: {"w": ["Silveryo"],                                           "ru": ["sam"]},
    66: {"w": ["AJ", "Benzo"],                                        "ru": []},
    67: {"w": ["Francis"],                                            "ru": ["JSoapz"]},
    68: {"w": ["Kay"],                                                "ru": []},
    69: {"w": ["Benzo"],                                              "ru": ["Gooby", "Zenon"]},
    70: {"w": [],                                                     "ru": []},
    71: {"w": ["Francis"],                                            "ru": ["Gooby"]},
    72: {"w": [],                                                     "ru": ["TR", "Mk"]},
    73: {"w": ["Fan(Esan)", "Mk"],                                    "ru": ["Francis"]},
    74: {"w": ["Kay"],                                                "ru": []},
    75: {"w": ["Gooby", "Matisse Thybulle"],                       "ru": ["Qrganic", "Gooby"]},
    76: {"w": ["Gooby"],                                           "ru": ["Benzo"]},
    77: {"w": ["Ferra", "Load", "Hilol"],                             "ru": ["Bony"]},
    78: {"w": ["Francis"],                                            "ru": ["Gooby", "jan"]},
    79: {"w": ["sorslab", "Qrganic"],                                 "ru": ["Mk", "AntGotNext"]},
    80: {"w": ["Gooby"],                                           "ru": ["Hayden", "manu"]},
    81: {"w": ["fearlessgolem", "Axyr"],                              "ru": ["Kay"]},
    82: {"w": ["Kay"],                                                "ru": ["udon"]},
    83: {"w": ["Admiral Ackbar"],                                     "ru": ["Mk", "AntGotNext"]},
    84: {"w": ["Ceo"],                                                "ru": ["Bony"]},
    85: {"w": ["Hilol", "ALLENSZN"],                                  "ru": ["Gooby"]},
    86: {"w": ["Matisse Thybulle", "Nate", "dmz"],                    "ru": ["Mk", "Deleted User"]},
    87: {"w": ["Admiral Ackbar", "Ceo"],                              "ru": ["Deleted User", "dmz"]},
    88: {"w": ["Blocked By Bam", "Mk"],                               "ru": []},
    89: {"w": ["dogboy", "ASoapz", "theo"],                          "ru": ["Deleted User"]},
    90: {"w": ["Admiral Ackbar", "sorslab"],                          "ru": ["Crispy"]},
    91: {"w": ["Kay"],                                                "ru": ["theo"]},
    92: {"w": ["Neto", "Suave"],                                      "ru": ["Francis"]},
    93: {"w": ["theo", "TR", "Silveryo", "Momo", "Jaymen", "Hayden", "JCMGAS"],
         "ru": ["Mk", "Aidan", "Hakeem Lowry", "M.", "Axyr", "Rick", "Fan(Esan)", "Matisse Thybulle"]},
    94: {"w": ["TR"],                                                 "ru": ["homer", "Mubs"]},
    95: {"w": ["TR"],                                                 "ru": ["Kay", "Francis"]},
    96: {"w": ["Silveryo", "Ryadad"],                                 "ru": ["Ceo"]},
    97: {"w": ["M."],                                                 "ru": ["Francis"]},
    98: {"w": ["Fan(Esan)", "Caliph"],                                "ru": ["Mk"]},
    99: {"w": ["the.klaw", "13enny", "JSoapz"],                       "ru": ["Hakeem Lowry", "Blocked By Bam"]},
    100:{"w": ["TR"],                                                 "ru": ["Crispy"]},
    101:{"w": ["Hakeem Lowry", "Qrganic", "Blocked By Bam"],            "ru": ["HT"]},
    102:{"w": ["Klaw"],                                                 "ru": ["Elpolo"]},
    103:{"w": ["Hayden", "Hilol"],                                      "ru": ["JSoapz"]},
    104:{"w": ["Bony"],                                                  "ru": ["Admiral Ackbar"]},
    105:{"w": ["HT", "Gooby"],                                          "ru": ["M.", "Axyr"]},
}

# Drafts whose championship is kept on record (still shown in !rings and the
# profile Championships tab) but excluded from win-count totals — e.g. a
# ghost draft that produced a technically-real but not-a-real-ring result.
MICKEY_RINGS = {
    89: "This is a mickey ring due to ghost draft and will not be counted as a real ring.",
}
