# champion_teams.py
# Winning team name (and, for pre-Sheet drafts, the full roster) for each ATD.
#
# For drafts already tracked in lottos.json, only "team" needs to be set here —
# the roster gets pulled live from lottos.json by team name.
#
# For older drafts with no lottos.json entry at all, the roster is stored
# directly here as "players": [{"name": ..., "year": ...}, ...].
#
# A handful of drafts (e.g. team drafts) had multiple co-winning teams. Those
# entries use "teams": [{"team": ..., "players": [...]}, ...] instead of a
# single "team"/"players" pair.

CHAMPION_TEAMS = {
    1: {
        "team": "New Vegas",
        "players": [
            {"name": "Jason Kidd",          "year": "2003-04"},
            {"name": "Luka Doncic",         "year": "2020-21"},
            {"name": "LeBron James",        "year": "2012-13"},
            {"name": "Amar'e Stoudemire",   "year": "2007-08"},
            {"name": "Dikembe Mutombo",     "year": "1995-96"},
            {"name": "Devin Booker",        "year": "2019-20"},
            {"name": "DeMar DeRozan",       "year": "2021-22"},
            {"name": "Matisse Thybulle",    "year": "2021-22"},
            {"name": "Myles Turner",        "year": "2019-20"},
            {"name": "Roy Hibbert",         "year": "2011-12"},
        ],
    },
    2: {
        "team": "LeSoapz",
        "players": [
            {"name": "Gary Payton",         "year": "1999-00"},
            {"name": "Ray Allen",           "year": "2000-01"},
            {"name": "Chris Mullin",        "year": "1990-91"},
            {"name": "Pau Gasol",           "year": "2005-06"},
            {"name": "Shaquille O'Neal",    "year": "1999-00"},
            {"name": "Nate Archibald",      "year": "1972-73"},
            {"name": "Adrian Dantley",      "year": "1982-83"},
            {"name": "Chet Walker",         "year": "1971-72"},
            {"name": "Bobby Jones",         "year": "1976-77"},
            {"name": "Rudy Gobert",         "year": "2019-20"},
        ],
    },
    3: {
        "team": "Dem Odell Chipz",
        "players": [
            {"name": "Damian Lillard",      "year": "2019-20"},
            {"name": "Sidney Moncrief",     "year": "1984-85"},
            {"name": "Klay Thompson",       "year": "2016-17"},
            {"name": "Draymond Green",      "year": "2015-16"},
            {"name": "Bill Russell",        "year": "1961-62"},
            {"name": "Rajon Rondo",         "year": "2015-16"},
            {"name": "Alvin Robertson",     "year": "1987-88"},
            {"name": "Glen Rice",           "year": "1996-97"},
            {"name": "Horace Grant",        "year": "1991-92"},
            {"name": "Dikembe Mutombo",     "year": "1993-94"},
        ],
    },
    4: {
        "team": "Dakota Ducks",
        "players": [
            {"name": "Chris Paul",          "year": "2013-14"},
            {"name": "Kobe Bryant",         "year": "2002-03"},
            {"name": "Tracy McGrady",       "year": "2002-03"},
            {"name": "Shawn Kemp",          "year": "1995-96"},
            {"name": "Bill Walton",         "year": "1976-77"},
            {"name": "Mookie Blaylock",     "year": "1996-97"},
            {"name": "Mitch Richmond",      "year": "1996-97"},
            {"name": "Shane Battier",       "year": "2006-07"},
            {"name": "Jayson Tatum",        "year": "2020-21"},
            {"name": "Arvydas Sabonis",     "year": "1996-97"},
        ],
    },
    5: {
        "team": "LeSoapz",
        "players": [
            {"name": "John Stockton",       "year": "1994-95"},
            {"name": "Michael Cooper",      "year": "1986-87"},
            {"name": "Grant Hill",          "year": "1996-97"},
            {"name": "Draymond Green",      "year": "2015-16"},
            {"name": "Tim Duncan",          "year": "2002-03"},
            {"name": "Tony Parker",         "year": "2001-02"},
            {"name": "Bradley Beal",        "year": "2019-20"},
            {"name": "Rip Hamilton",        "year": "2005-06"},
            {"name": "Dominique Wilkins",   "year": "1985-86"},
            {"name": "Tyson Chandler",      "year": "2011-12"},
        ],
    },
    6: {
        "team": "DEEZ BONES",
        "players": [
            {"name": "Luka Doncic",         "year": "2020-21"},
            {"name": "Danny Green",         "year": "2012-13"},
            {"name": "Andre Iguodala",      "year": "2011-12"},
            {"name": "LeBron James",        "year": "2012-13"},
            {"name": "Karl-Anthony Towns",  "year": "2019-20"},
            {"name": "Ja Morant",           "year": "2020-21"},
            {"name": "Marcus Smart",        "year": "2020-21"},
            {"name": "Jerami Grant",        "year": "2020-21"},
            {"name": "Jaren Jackson Jr.",   "year": "2018-19"},
            {"name": "Hassan Whiteside",    "year": "2015-16"},
        ],
    },
    7: {
        "team": "Phoenix Suns",
        "players": [
            {"name": "Chris Paul",          "year": "2008-09"},
            {"name": "Ray Allen",           "year": "2000-01"},
            {"name": "LeBron James",        "year": "2012-13"},
            {"name": "Charles Barkley",     "year": "1992-93"},
            {"name": "DeAndre Jordan",      "year": "2014-15"},
            {"name": "Tony Parker",         "year": "2001-02"},
            {"name": "Raja Bell",           "year": "2005-06"},
            {"name": "Luol Deng",           "year": "2010-11"},
            {"name": "Amar'e Stoudemire",   "year": "2004-05"},
            {"name": "Vlade Divac",         "year": "1994-95"},
        ],
    },
    8: {
        "team": "LeSoapz",
        "players": [
            {"name": "Luka Doncic",         "year": "2019-20"},
            {"name": "Klay Thompson",       "year": "2015-16"},
            {"name": "LeBron James",        "year": "2012-13"},
            {"name": "Draymond Green",      "year": "2015-16"},
            {"name": "David Robinson",      "year": "1993-94"},
            {"name": "Isiah Thomas",        "year": "1984-85"},
            {"name": "Sidney Moncrief",     "year": "1984-85"},
            {"name": "Grant Hill",          "year": "1996-97"},
            {"name": "Karl-Anthony Towns",  "year": "2020-21"},
            {"name": "Joel Embiid",         "year": "2020-21"},
        ],
    },
    # 9 = NFL, 10 = Cancelled
    11: {
        "team": "LeSoapz",
        "players": [
            {"name": "Mike Conley",         "year": "2016-17"},
            {"name": "Sidney Moncrief",     "year": "1984-85"},
            {"name": "Klay Thompson",       "year": "2015-16"},
            {"name": "Kevin Durant",        "year": "2016-17"},
            {"name": "Rudy Gobert",         "year": "2019-20"},
            {"name": "Mark Price",          "year": "1988-89"},
            {"name": "Alvin Robertson",     "year": "1985-86"},
            {"name": "Tayshaun Prince",     "year": "2003-04"},
            {"name": "Amar'e Stoudemire",   "year": "2007-08"},
            {"name": "Jermaine O'Neal",     "year": "2002-03"},
        ],
    },
    12: {
        "team": "LeSoapz",
        "players": [
            {"name": "Jason Kidd",          "year": "2002-03"},
            {"name": "Sidney Moncrief",     "year": "1984-85"},
            {"name": "Kevin Durant",        "year": "2015-16"},
            {"name": "Dirk Nowitzki",       "year": "2005-06"},
            {"name": "Moses Malone",        "year": "1980-81"},
            {"name": "Terry Porter",        "year": "1988-89"},
            {"name": "Avery Bradley",       "year": "2016-17"},
            {"name": "Dominique Wilkins",   "year": "1992-93"},
            {"name": "Antoine Walker",      "year": "2000-01"},
            {"name": "Horace Grant",        "year": "1991-92"},
        ],
    },
    13: {
        "team": "Raptors",
        "players": [
            {"name": "James Harden",        "year": "2018-19"},
            {"name": "Sidney Moncrief",     "year": "1984-85"},
            {"name": "Glen Rice",           "year": "1996-97"},
            {"name": "Kevin Garnett",       "year": "2003-04"},
            {"name": "Dikembe Mutombo",     "year": "1993-94"},
            {"name": "Baron Davis",         "year": "2003-04"},
            {"name": "Latrell Sprewell",    "year": "1996-97"},
            {"name": "Andrei Kirilenko",    "year": "2003-04"},
            {"name": "Serge Ibaka",         "year": "2013-14"},
            {"name": "Rudy Gobert",         "year": "2018-19"},
        ],
    },
    14: {
        "team": "Age is just a number",
        "players": [
            {"name": "Chris Paul",          "year": "2014-15"},
            {"name": "Joe Johnson",         "year": "2007-08"},
            {"name": "Nicolas Batum",       "year": "2012-13"},
            {"name": "Kevin Love",          "year": "2013-14"},
            {"name": "DeMarcus Cousins",    "year": "2016-17"},
            {"name": "Kemba Walker",        "year": "2018-19"},
            {"name": "Eric Gordon",         "year": "2017-18"},
            {"name": "Rudy Gay",            "year": "2010-11"},
            {"name": "Danilo Gallinari",    "year": "2018-19"},
            {"name": "JaVale McGee",        "year": "2018-19"},
        ],
    },
    15: {
        "team": "Bizzy",
        "players": [
            {"name": "James Harden",       "year": "2020-21"},
            {"name": "Paul George",        "year": "2018-19"},
            {"name": "Rashard Lewis",      "year": "2006-07"},
            {"name": "Chris Bosh",         "year": "2014-15"},
            {"name": "Nate Thurmond",      "year": "1971-72"},
            {"name": "Nate Archibald",     "year": "1972-73"},
            {"name": "Dan Majerle",        "year": "1995-96"},
            {"name": "Khris Middleton",    "year": "2017-18"},
            {"name": "Lamar Odom",         "year": "2005-06"},
            {"name": "Dikembe Mutombo",    "year": "1992-93"},
        ],
    },
    16: {
        "team": "Dreamville",
        "players": [
            {"name": "Isiah Thomas",       "year": "1984-85"},
            {"name": "Paul George",        "year": "2018-19"},
            {"name": "Scottie Pippen",     "year": "1993-94"},
            {"name": "Karl-Anthony Towns", "year": "2020-21"},
            {"name": "Anthony Davis",      "year": "2019-20"},
            {"name": "Darius Garland",     "year": "2021-22"},
            {"name": "Lonzo Ball",         "year": "2021-22"},
            {"name": "Bruce Bowen",        "year": "2002-03"},
            {"name": "Ben Simmons",        "year": "2019-20"},
            {"name": "Robert Parish",      "year": "1981-82"},
        ],
    },
    17: {
        "team": "SDP",
        "players": [
            {"name": "John Stockton",      "year": "1988-89"},
            {"name": "Danny Green",        "year": "2014-15"},
            {"name": "Peja Stojaković",    "year": "2003-04"},
            {"name": "Kevin Garnett",      "year": "2003-04"},
            {"name": "Shaquille O'Neal",   "year": "1999-00"},
            {"name": "Darius Garland",     "year": "2021-22"},
            {"name": "Marcus Smart",       "year": "2021-22"},
            {"name": "Joe Johnson",        "year": "2006-07"},
            {"name": "Bob Love",           "year": "1970-71"},
            {"name": "Mark Eaton",         "year": "1984-85"},
        ],
    },
    18: {
        "team": "The RTB Clamps",
        "players": [
            {"name": "Chauncey Billups",       "year": "2005-06"},
            {"name": "Sam Jones",              "year": "1964-65"},
            {"name": "Jaylen Brown",           "year": "2020-21"},
            {"name": "Dirk Nowitzki",          "year": "2006-07"},
            {"name": "Kareem Abdul-Jabbar",    "year": "1970-71"},
            {"name": "Gary Payton",            "year": "1999-00"},
            {"name": "Shai Gilgeous-Alexander","year": "2020-21"},
            {"name": "Sean Elliott",           "year": "1995-96"},
            {"name": "Clifford Robinson",      "year": "1994-95"},
            {"name": "Robert Parish",          "year": "1981-82"},
        ],
    },
    21: {
        "team": "Miami Herro Ball",
        "players": [
            {"name": "Chauncey Billups",   "year": "2005-06"},
            {"name": "Peja Stojaković",    "year": "2003-04"},
            {"name": "LeBron James",       "year": "2012-13"},
            {"name": "Chris Bosh",         "year": "2009-10"},
            {"name": "Dave Cowens",        "year": "1974-75"},
            {"name": "Gilbert Arenas",     "year": "2005-06"},
            {"name": "Michael Cooper",     "year": "1986-87"},
            {"name": "Gordon Hayward",     "year": "2016-17"},
            {"name": "Lamar Odom",         "year": "2003-04"},
            {"name": "Mark Eaton",         "year": "1984-85"},
        ],
    },
    24: {
        "team": "Soap",
        "players": [
            {"name": "Mike Conley",        "year": "2016-17"},
            {"name": "Kyrie Irving",       "year": "2020-21"},
            {"name": "Paul George",        "year": "2018-19"},
            {"name": "Zion Williamson",    "year": "2020-21"},
            {"name": "Myles Turner",       "year": "2019-20"},
            {"name": "Tyrese Maxey",       "year": "2022-23"},
            {"name": "Gary Payton II",     "year": "2021-22"},
            {"name": "PJ Tucker",          "year": "2018-19"},
            {"name": "Keegan Murray",      "year": "2022-23"},
            {"name": "Mitchell Robinson",  "year": "2019-20"},
        ],
    },
    25: {
        "team": "DeMarcus Cousins III",
        "players": [
            {"name": "Magic Johnson",      "year": "1986-87"},
            {"name": "Clyde Drexler",      "year": "1991-92"},
            {"name": "Rick Barry",         "year": "1974-75"},
            {"name": "Kevin Love",         "year": "2013-14"},
            {"name": "Shaquille O'Neal",   "year": "1999-00"},
            {"name": "Maurice Cheeks",     "year": "1985-86"},
            {"name": "David Thompson",     "year": "1977-78"},
            {"name": "Tony Allen",         "year": "2014-15"},
            {"name": "Keegan Murray",      "year": "2022-23"},
            {"name": "Alvin Adams",        "year": "1975-76"},
        ],
    },
    26: {
        "team": "DAMN",
        "players": [
            {"name": "Jason Kidd",             "year": "1998-99"},
            {"name": "Kyle Korver",            "year": "2013-14"},
            {"name": "LeBron James",           "year": "2012-13"},
            {"name": "Anthony Davis",          "year": "2019-20"},
            {"name": "David Robinson",         "year": "1994-95"},
            {"name": "Deron Williams",         "year": "2012-13"},
            {"name": "John Havlicek",          "year": "1970-71"},
            {"name": "Paul Pierce",            "year": "2001-02"},
            {"name": "Giannis Antetokounmpo",  "year": "2019-20"},
            {"name": "Marc Gasol",             "year": "2016-17"},
        ],
    },
    27: {
        "team": "France",
        "players": [
            {"name": "Mike Conley",        "year": "2016-17"},
            {"name": "Manu Ginóbili",      "year": "2007-08"},
            {"name": "Kawhi Leonard",      "year": "2016-17"},
            {"name": "Dennis Rodman",      "year": "1994-95"},
            {"name": "David Robinson",     "year": "1993-94"},
            {"name": "Damian Lillard",     "year": "2016-17"},
            {"name": "George Gervin",      "year": "1979-80"},
            {"name": "Bruce Bowen",        "year": "2004-05"},
            {"name": "Robert Horry",       "year": "2004-05"},
            {"name": "LaMarcus Aldridge",  "year": "2017-18"},
        ],
    },
    28: {
        "team": "Wizards",
        "players": [
            {"name": "Damian Lillard",     "year": "2019-20"},
            {"name": "Klay Thompson",      "year": "2015-16"},
            {"name": "LeBron James",       "year": "2012-13"},
            {"name": "Rasheed Wallace",    "year": "2001-02"},
            {"name": "Moses Malone",       "year": "1981-82"},
            {"name": "James Harden",       "year": "2018-19"},
            {"name": "Joe Dumars",         "year": "1992-93"},
            {"name": "Shawn Marion",       "year": "2005-06"},
            {"name": "Karl-Anthony Towns", "year": "2021-22"},
            {"name": "Joakim Noah",        "year": "2013-14"},
        ],
    },
    29: {
        "team": "Sleepy Snorlax",
        "players": [
            {"name": "Isiah Thomas",       "year": "1984-85"},
            {"name": "Paul George",        "year": "2018-19"},
            {"name": "Scottie Pippen",     "year": "1993-94"},
            {"name": "Karl-Anthony Towns", "year": "2021-22"},
            {"name": "Anthony Davis",      "year": "2019-20"},
            {"name": "Tyrese Maxey",       "year": "2022-23"},
            {"name": "Gary Payton II",     "year": "2021-22"},
            {"name": "Bruce Bowen",        "year": "2002-03"},
            {"name": "Ben Simmons",        "year": "2019-20"},
            {"name": "Robert Parish",      "year": "1981-82"},
        ],
    },
    31: {
        "team": "France",
        "players": [
            {"name": "Isiah Thomas",       "year": "1984-85"},
            {"name": "Vince Carter",       "year": "2000-01"},
            {"name": "Jayson Tatum",       "year": "2022-23"},
            {"name": "Pascal Siakam",      "year": "2019-20"},
            {"name": "Wilt Chamberlain",   "year": "1966-67"},
            {"name": "Penny Hardaway",     "year": "1995-96"},
            {"name": "JJ Redick",          "year": "2018-19"},
            {"name": "OG Anunoby",         "year": "2022-23"},
            {"name": "Ben Simmons",        "year": "2019-20"},
            {"name": "Joel Embiid",        "year": "2022-23"},
        ],
    },
    32: {
        "team": "ICE WALLOW COME",
        "players": [
            {"name": "Michael Jordan",     "year": "1987-88"},
            {"name": "Michael Cooper",     "year": "1986-87"},
            {"name": "Julius Erving",      "year": "1981-82"},
            {"name": "Bobby Jones",        "year": "1981-82"},
            {"name": "Moses Malone",       "year": "1982-83"},
            {"name": "Isiah Thomas",       "year": "1984-85"},
            {"name": "Derek Harper",       "year": "1986-87"},
            {"name": "Dale Ellis",         "year": "1988-89"},
            {"name": "Kevin McHale",       "year": "1986-87"},
            {"name": "Jack Sikma",         "year": "1981-82"},
        ],
    },
    34: {
        "team": "LeBronson Johnson Ballers",
        "players": [
            {"name": "Damian Lillard",     "year": "2019-20"},
            {"name": "Klay Thompson",      "year": "2015-16"},
            {"name": "Kevin Durant",       "year": "2016-17"},
            {"name": "Draymond Green",     "year": "2015-16"},
            {"name": "Patrick Ewing",      "year": "1989-90"},
            {"name": "Darius Garland",     "year": "2021-22"},
            {"name": "Danny Green",        "year": "2014-15"},
            {"name": "Danny Granger",      "year": "2008-09"},
            {"name": "Chris Bosh",         "year": "2012-13"},
            {"name": "Artis Gilmore",      "year": "1974-75"},
        ],
    },
    35: {
        "team": "Knicks",
        "players": [
            {"name": "John Stockton",      "year": "1990-91"},
            {"name": "Michael Jordan",     "year": "1990-91"},
            {"name": "Mitch Richmond",     "year": "1996-97"},
            {"name": "Andrew Wiggins",     "year": "2021-22"},
            {"name": "Patrick Ewing",      "year": "1989-90"},
            {"name": "Kirk Hinrich",       "year": "2006-07"},
            {"name": "Anthony Edwards",    "year": "2022-23"},
            {"name": "James Posey",        "year": "2003-04"},
            {"name": "Jerami Grant",       "year": "2022-23"},
            {"name": "Kristaps Porzingis", "year": "2022-23"},
        ],
    },
    36: {
        "team": "Knicks",
        "players": [
            {"name": "Oscar Robertson",    "year": "1963-64"},
            {"name": "Danny Green",        "year": "2014-15"},
            {"name": "Khris Middleton",    "year": "2019-20"},
            {"name": "Tim Duncan",         "year": "2002-03"},
            {"name": "Kareem Abdul-Jabbar","year": "1970-71"},
            {"name": "Penny Hardaway",     "year": "1996-97"},
            {"name": "Derek Harper",       "year": "1986-87"},
            {"name": "Michael Redd",       "year": "2005-06"},
            {"name": "Jaren Jackson Jr.",  "year": "2022-23"},
            {"name": "Robert Parish",      "year": "1980-81"},
        ],
    },
    37: {
        # Sheet header for this team literally reads "N/A" — confirmed real
        # name is "TK Fanclub".
        "team": "TK Fanclub",
        "players": [
            {"name": "Russell Westbrook",  "year": "2016-17"},
            {"name": "Paul George",        "year": "2018-19"},
            {"name": "Kawhi Leonard",      "year": "2015-16"},
            {"name": "Robert Covington",   "year": "2018-19"},
            {"name": "Tyson Chandler",     "year": "2010-11"},
            {"name": "Fred VanVleet",      "year": "2021-22"},
            {"name": "Dejounte Murray",    "year": "2021-22"},
            {"name": "OG Anunoby",         "year": "2022-23"},
            {"name": "Pascal Siakam",      "year": "2022-23"},
            {"name": "Serge Ibaka",        "year": "2012-13"},
        ],
    },
    38: {
        "team": "#1 in the Nation",
        "players": [
            {"name": "Steve Nash",         "year": "2006-07"},
            {"name": "Manu Ginóbili",      "year": "2004-05"},
            {"name": "Andre Iguodala",     "year": "2011-12"},
            {"name": "Anthony Davis",      "year": "2019-20"},
            {"name": "Marc Gasol",         "year": "2012-13"},
            {"name": "Tyrese Haliburton",  "year": "2022-23"},
            {"name": "Richard Hamilton",   "year": "2005-06"},
            {"name": "Luol Deng",          "year": "2010-11"},
            {"name": "Chris Webber",       "year": "1999-00"},
            {"name": "Dave Cowens",        "year": "1974-75"},
        ],
    },
    39: {
        "team": "AJ",
        "players": [
            {"name": "Oscar Robertson",    "year": "1964-65"},
            {"name": "Joe Dumars",         "year": "1992-93"},
            {"name": "Tayshaun Prince",    "year": "2005-06"},
            {"name": "Toni Kukoc",         "year": "1995-96"},
            {"name": "Wilt Chamberlain",   "year": "1966-67"},
            {"name": "Tim Hardaway Sr.",   "year": "1996-97"},
            {"name": "Walter Davis",       "year": "1978-79"},
            {"name": "Dick Van Arsdale",   "year": "1973-74"},
            {"name": "Brad Miller",        "year": "2003-04"},
            {"name": "Marcus Camby",       "year": "2006-07"},
        ],
    },
    40: {
        "team": "Dreamville",
        "players": [
            {"name": "Walt Frazier",       "year": "1971-72"},
            {"name": "Kobe Bryant",        "year": "2007-08"},
            {"name": "Luol Deng",          "year": "2010-11"},
            {"name": "Rasheed Wallace",    "year": "2001-02"},
            {"name": "Bill Russell",       "year": "1961-62"},
            {"name": "Avery Bradley",      "year": "2016-17"},
            {"name": "Jamal Murray",       "year": "2022-23"},
            {"name": "Trey Murphy",        "year": "2022-23"},
            {"name": "Toni Kukoc",         "year": "1995-96"},
            {"name": "Brook Lopez",        "year": "2022-23"},
        ],
    },
    41: {
        "team": "Detroit Pistons",
        "players": [
            {"name": "Michael Jordan",     "year": "1990-91"},
            {"name": "Michael Cooper",     "year": "1986-87"},
            {"name": "Mikal Bridges",      "year": "2022-23"},
            {"name": "Scottie Pippen",     "year": "1993-94"},
            {"name": "Rudy Gobert",        "year": "2020-21"},
            {"name": "Ja Morant",          "year": "2021-22"},
            {"name": "Kirk Hinrich",       "year": "2006-07"},
            {"name": "George Gervin",      "year": "1978-79"},
            {"name": "Jamaal Wilkes",      "year": "1979-80"},
            {"name": "Brad Miller",        "year": "2003-04"},
        ],
    },
    42: {
        "team": "Spurs",
        "players": [
            {"name": "Kyrie Irving",       "year": "2020-21"},
            {"name": "Michael Jordan",     "year": "1990-91"},
            {"name": "Dan Majerle",        "year": "1992-93"},
            {"name": "Ron Artest",         "year": "2002-03"},
            {"name": "Moses Malone",       "year": "1982-83"},
            {"name": "Mookie Blaylock",    "year": "1995-96"},
            {"name": "CJ McCollum",        "year": "2020-21"},
            {"name": "David Thompson",     "year": "1977-78"},
            {"name": "Josh Smith",         "year": "2011-12"},
            {"name": "Vlade Divac",        "year": "1998-99"},
        ],
    },
    43: {
        "team": "Guangdong Tigers",
        "players": [
            {"name": "Kyle Lowry",             "year": "2016-17"},
            {"name": "Michael Cooper",         "year": "1986-87"},
            {"name": "Vince Carter",           "year": "2000-01"},
            {"name": "Giannis Antetokounmpo",  "year": "2021-22"},
            {"name": "Bill Russell",           "year": "1961-62"},
            {"name": "Fat Lever",              "year": "1987-88"},
            {"name": "Dick Van Arsdale",        "year": "1969-70"},
            {"name": "Nicolas Batum",          "year": "2013-14"},
            {"name": "Bobby Jones",            "year": "1976-77"},
            {"name": "Chris Webber",           "year": "1996-97"},
        ],
    },
    44: {
        "team": "Dreamville",
        "players": [
            {"name": "Walt Frazier",              "year": "1971-72"},
            {"name": "Jeff Hornacek",             "year": "1991-92"},
            {"name": "Scottie Pippen",            "year": "1993-94"},
            {"name": "Toni Kukoc",                "year": "1995-96"},
            {"name": "Patrick Ewing",             "year": "1989-90"},
            {"name": "Shai Gilgeous-Alexander",   "year": "2022-23"},
            {"name": "Gary Payton II",            "year": "2021-22"},
            {"name": "Kiki Vandeweghe",           "year": "1983-84"},
            {"name": "Jae Crowder",               "year": "2016-17"},
            {"name": "Evan Mobley",               "year": "2022-23"},
        ],
    },
    47: {
        "team": "B and B",
        "players": [
            {"name": "Jalen Brunson",      "year": "2023-24"},
            {"name": "Devin Vassell",      "year": "2023-24"},
            {"name": "Jaden McDaniels",    "year": "2023-24"},
            {"name": "Rasheed Wallace",    "year": "2001-02"},
            {"name": "Jarrett Allen",      "year": "2021-22"},
            {"name": "Tyus Jones",         "year": "2023-24"},
            {"name": "Max Strus",          "year": "2022-23"},
            {"name": "RJ Barrett",         "year": "2023-24"},
            {"name": "Rui Hachimura",      "year": "2023-24"},
            {"name": "Nic Claxton",        "year": "2023-24"},
        ],
    },
    49: {
        "team": "Olivia Rodrigirls",
        "players": [
            {"name": "Shai Gilgeous-Alexander","year": "2022-23"},
            {"name": "Paul George",            "year": "2018-19"},
            {"name": "Andre Iguodala",         "year": "2011-12"},
            {"name": "Rasheed Wallace",        "year": "2001-02"},
            {"name": "Larry Nance Sr.",        "year": "1991-92"},
            {"name": "Terrell Brandon",        "year": "1995-96"},
            {"name": "Desmond Bane",           "year": "2022-23"},
            {"name": "Lou Hudson",             "year": "1969-70"},
            {"name": "Boris Diaw",             "year": "2005-06"},
            {"name": "Arvydas Sabonis",        "year": "1997-98"},
        ],
    },
    50: {
        "team": "Syracuse",
        "players": [
            {"name": "Kyrie Irving",       "year": "2020-21"},
            {"name": "Sidney Moncrief",    "year": "1982-83"},
            {"name": "Mikal Bridges",      "year": "2022-23"},
            {"name": "LeBron James",       "year": "2012-13"},
            {"name": "Jack Sikma",         "year": "1981-82"},
            {"name": "Hal Greer",          "year": "1967-68"},
            {"name": "Kirk Hinrich",       "year": "2006-07"},
            {"name": "Thabo Sefolosha",    "year": "2012-13"},
            {"name": "Dominique Wilkins",  "year": "1992-93"},
            {"name": "Dikembe Mutombo",    "year": "1993-94"},
        ],
    },
    33: {
        "team": "Los Angeles Clippers",
        "players": [
            {"name": "Mike Conley",        "year": "2016-17"},
            {"name": "Eddie Jones",        "year": "1999-00"},
            {"name": "Paul George",        "year": "2018-19"},
            {"name": "Charles Barkley",    "year": "1992-93"},
            {"name": "Bill Russell",       "year": "1961-62"},
            {"name": "Kevin Johnson",      "year": "1990-91"},
            {"name": "Dennis Johnson",     "year": "1980-81"},
            {"name": "Nicolas Batum",      "year": "2013-14"},
            {"name": "Joe Ingles",         "year": "2017-18"},
            {"name": "Horace Grant",       "year": "1991-92"},
        ],
    },
    46: {
        "team": "Beans",
        # This draft used a special "2 Peaks" format with separate Offense/Defense
        # years per player. Storing the Offense year as the canonical "year".
        "players": [
            {"name": "Terry Porter",       "year": "1990-91"},
            {"name": "Jimmy Butler",       "year": "2021-22"},
            {"name": "Kawhi Leonard",      "year": "2020-21"},
            {"name": "Jaren Jackson Jr.",  "year": "2019-20"},
            {"name": "Alonzo Mourning",    "year": "1999-00"},
            {"name": "Goran Dragic",       "year": "2016-17"},
            {"name": "Lonzo Ball",         "year": "2021-22"},
            {"name": "Otto Porter Jr.",    "year": "2017-18"},
            {"name": "David West",         "year": "2009-10"},
            {"name": "Vlade Divac",        "year": "1990-91"},
        ],
    },
    45: {
        "team": "Dreamville",
        "players": [
            {"name": "Jerry West",         "year": "1967-68"},
            {"name": "Jimmy Butler",       "year": "2016-17"},
            {"name": "Andre Iguodala",     "year": "2011-12"},
            {"name": "Rasheed Wallace",    "year": "2003-04"},
            {"name": "David Robinson",     "year": "1990-91"},
            {"name": "Tim Hardaway Sr.",   "year": "1990-91"},
            {"name": "Alex Caruso",        "year": "2022-23"},
            {"name": "Herb Jones",         "year": "2022-23"},
            {"name": "Kristaps Porzingis", "year": "2022-23"},
            {"name": "Andrew Bogut",       "year": "2009-10"},
        ],
    },
    51: {
        "team": "Wizards",
        "players": [
            {"name": "Dwyane Wade",        "year": "2008-09"},
            {"name": "Eddie Jones",        "year": "1999-00"},
            {"name": "Paul Pierce",        "year": "2007-08"},
            {"name": "Giannis Antetokounmpo","year": "2021-22"},
            {"name": "Dave Cowens",        "year": "1974-75"},
            {"name": "Danny Ainge",        "year": "1987-88"},
            {"name": "Jerry Sloan",        "year": "1970-71"},
            {"name": "Caron Butler",       "year": "2007-08"},
            {"name": "Dave DeBusschere",   "year": "1971-72"},
            {"name": "Kristaps Porzingis", "year": "2022-23"},
        ],
    },
    52: {
        "team": "76ers",
        "players": [
            {"name": "James Harden",       "year": "2019-20"},
            {"name": "Derrick White",      "year": "2022-23"},
            {"name": "Gordon Hayward",     "year": "2016-17"},
            {"name": "Luol Deng",          "year": "2010-11"},
            {"name": "Rudy Gobert",        "year": "2020-21"},
            {"name": "Allen Iverson",      "year": "2000-01"},
            {"name": "Wesley Matthews",    "year": "2014-15"},
            {"name": "Glen Rice",          "year": "1996-97"},
            {"name": "Lamar Odom",         "year": "2008-09"},
            {"name": "Robert Parish",      "year": "1980-81"},
        ],
    },
    53: {
        "team": "Iowa",
        "players": [
            {"name": "Luka Doncic",        "year": "2022-23"},
            {"name": "Jaylen Brown",       "year": "2020-21"},
            {"name": "Wesley Person",      "year": "1997-98"},
            {"name": "Chris Webber",       "year": "2001-02"},
            {"name": "Artis Gilmore",      "year": "1971-72"},
            {"name": "Sleepy Floyd",       "year": "1986-87"},
            {"name": "Michael Redd",       "year": "2005-06"},
            {"name": "Thabo Sefolosha",    "year": "2012-13"},
            {"name": "Clifford Robinson",  "year": "1999-00"},
            {"name": "Antonio McDyess",    "year": "1998-99"},
        ],
    },
    54: {
        "team": "Cavs",
        "players": [
            {"name": "Ja Morant",          "year": "2021-22"},
            {"name": "Jerry West",         "year": "1967-68"},
            {"name": "Danny Granger",      "year": "2008-09"},
            {"name": "Shawn Marion",       "year": "2005-06"},
            {"name": "Hakeem Olajuwon",    "year": "1993-94"},
            {"name": "Fred VanVleet",      "year": "2021-22"},
            {"name": "Byron Scott",        "year": "1987-88"},
            {"name": "Jaden McDaniels",    "year": "2022-23"},
            {"name": "Carmelo Anthony",    "year": "2012-13"},
            {"name": "Andrew Bogut",       "year": "2009-10"},
        ],
    },
    55: {
        "team": "Steamrollers",
        "players": [
            {"name": "Gary Payton",        "year": "2000-01"},
            {"name": "Michael Jordan",     "year": "1990-91"},
            {"name": "Rick Barry",         "year": "1974-75"},
            {"name": "Lauri Markkanen",    "year": "2022-23"},
            {"name": "Patrick Ewing",      "year": "1989-90"},
            {"name": "Jo Jo White",        "year": "1975-76"},
            {"name": "Dick Van Arsdale",   "year": "1969-70"},
            {"name": "Cedric Maxwell",     "year": "1979-80"},
            {"name": "Kristaps Porzingis", "year": "2022-23"},
            {"name": "Bill Laimbeer",      "year": "1984-85"},
        ],
    },
    56: {
        "team": "Iowa",
        "players": [
            {"name": "Isiah Thomas",       "year": "1984-85"},
            {"name": "Kawhi Leonard",      "year": "2020-21"},
            {"name": "Rick Barry",         "year": "1969-70"},
            {"name": "Paul Millsap",       "year": "2010-11"},
            {"name": "Patrick Ewing",      "year": "1989-90"},
            {"name": "Darius Garland",     "year": "2021-22"},
            {"name": "Dick Van Arsdale",   "year": "1969-70"},
            {"name": "Elgin Baylor",       "year": "1962-63"},
            {"name": "Kristaps Porzingis", "year": "2017-18"},
            {"name": "Bill Walton",        "year": "1985-86"},
        ],
    },
    57: {
        "team": "Spurs",
        "players": [
            {"name": "Kyle Lowry",         "year": "2016-17"},
            {"name": "Desmond Bane",       "year": "2022-23"},
            {"name": "Julius Erving",      "year": "1975-76"},
            {"name": "Scottie Pippen",     "year": "1993-94"},
            {"name": "Alonzo Mourning",    "year": "1999-00"},
            {"name": "Dennis Johnson",     "year": "1981-82"},
            {"name": "Joe Johnson",        "year": "2006-07"},
            {"name": "Elgin Baylor",       "year": "1962-63"},
            {"name": "Thabo Sefolosha",    "year": "2012-13"},
            {"name": "Arvydas Sabonis",    "year": "1997-98"},
        ],
    },
    58: {
        "team": "Syracuse",
        "players": [
            {"name": "Mike Conley",        "year": "TBD"},
            {"name": "Kyrie Irving",       "year": "2020-21"},
            {"name": "Tracy McGrady",      "year": "2002-03"},
            {"name": "Jayson Tatum",       "year": "2022-23"},
            {"name": "Rudy Gobert",        "year": "2020-21"},
            {"name": "Louis Dampier",      "year": "TBD"},
            {"name": "Anthony Edwards",    "year": "2022-23"},
            {"name": "Wesley Person",      "year": "1997-98"},
            {"name": "Dave DeBusschere",   "year": "1969-70"},
            {"name": "Dikembe Mutombo",    "year": "1993-94"},
        ],
    },
    59: {
        # No team literally named "Texas" in this sheet — matched to "Longhorns",
        # consistent with the "Texas" -> "Texas Longhorns" naming used for ATD 1.
        "team": "Texas Longhorns",
        "players": [
            {"name": "Shai Gilgeous-Alexander","year": "2022-23"},
            {"name": "Eddie Jones",            "year": "1999-00"},
            {"name": "Grant Hill",             "year": "1996-97"},
            {"name": "Paul Millsap",           "year": "2014-15"},
            {"name": "Anthony Davis",          "year": "2019-20"},
            {"name": "Fat Lever",              "year": "1986-87"},
            {"name": "Jon McGlocklin",         "year": "1968-69"},
            {"name": "Zach LaVine",            "year": "2020-21"},
            {"name": "Alvan Adams",            "year": "1975-76"},
            {"name": "Theo Ratliff",           "year": "2000-01"},
        ],
    },
    60: {
        "team": "Jazz",
        "players": [
            {"name": "Jrue Holiday",       "year": "2021-22"},
            {"name": "Bradley Beal",       "year": "2020-21"},
            {"name": "Tracy McGrady",      "year": "2002-03"},
            {"name": "Pascal Siakam",      "year": "2018-19"},
            {"name": "Bill Walton",        "year": "1976-77"},
            {"name": "Derrick Rose",       "year": "2010-11"},
            {"name": "Hal Greer",          "year": "1967-68"},
            {"name": "OG Anunoby",         "year": "2022-23"},
            {"name": "Kevin Love",         "year": "2013-14"},
            {"name": "Andrew Bogut",       "year": "2009-10"},
        ],
    },
    61: {
        "team": "UC Santa Cruz Banana",
        "players": [
            {"name": "Deron Williams",     "year": "2009-10"},
            {"name": "Hersey Hawkins",     "year": "1996-97"},
            {"name": "Luol Deng",          "year": "2010-11"},
            {"name": "Charles Barkley",    "year": "1992-93"},
            {"name": "David Robinson",     "year": "1994-95"},
            {"name": "Mookie Blaylock",    "year": "1996-97"},
            {"name": "Latrell Sprewell",   "year": "1993-94"},
            {"name": "Andrew Wiggins",     "year": "2021-22"},
            {"name": "Bob Pettit",         "year": "1958-59"},
            {"name": "P.J. Brown",         "year": "2000-01"},
        ],
    },
    "61-D2": {
        "team": "Lakers",
        "players": [
            {"name": "Tyrese Haliburton", "year": "2023-24"},
            {"name": "Kobe Bryant",        "year": "2007-08"},
            {"name": "Paul Pierce",        "year": "2007-08"},
            {"name": "Andrei Kirilenko",   "year": "2003-04"},
            {"name": "Karl-Anthony Towns", "year": "2021-22"},
            {"name": "Terrell Brandon",    "year": "1995-96"},
            {"name": "David Thompson",     "year": "1977-78"},
            {"name": "Steve Smith",        "year": "1997-98"},
            {"name": "Antonio McDyess",    "year": "1997-98"},
            {"name": "Jarrett Allen",      "year": "2023-24"},
        ],
    },
    "62-D2": {
        "team": "Bulls",
        "players": [
            {"name": "Fat Lever",          "year": "1987-88"},
            {"name": "Victor Oladipo",     "year": "2017-18"},
            {"name": "Danny Granger",      "year": "2008-09"},
            {"name": "Kevin Durant",       "year": "2016-17"},
            {"name": "Bill Russell",       "year": "1961-62"},
            {"name": "Rod Strickland",     "year": "1994-95"},
            {"name": "Kirk Hinrich",       "year": "2006-07"},
            {"name": "Bob Dandridge",      "year": "1973-74"},
            {"name": "Danilo Gallinari",   "year": "2018-19"},
            {"name": "Jermaine O'Neal",    "year": "2003-04"},
        ],
    },
    63: {
        "team": "Houston Rockets",
        "players": [
            {"name": "Chauncey Billups",   "year": "2005-06"},
            {"name": "Bradley Beal",       "year": "2020-21"},
            {"name": "Marques Johnson",    "year": "1980-81"},
            {"name": "LeBron James",       "year": "2012-13"},
            {"name": "Nate Thurmond",      "year": "1968-69"},
            {"name": "Danny Ainge",        "year": "1987-88"},
            {"name": "Steve Smith",        "year": "1997-98"},
            {"name": "Thabo Sefolosha",    "year": "2012-13"},
            {"name": "Jamal Mashburn",     "year": "1999-00"},
            {"name": "Arvydas Sabonis",    "year": "1997-98"},
        ],
    },
    "63-D2": {
        "team": "Spurs",
        "players": [
            {"name": "Kyrie Irving",       "year": "2020-21"},
            {"name": "Mikal Bridges",      "year": "2022-23"},
            {"name": "LeBron James",       "year": "2012-13"},
            {"name": "Scottie Pippen",     "year": "1993-94"},
            {"name": "Marc Gasol",         "year": "2012-13"},
            {"name": "Baron Davis",        "year": "2006-07"},
            {"name": "Jason Terry",        "year": "2006-07"},
            {"name": "Michael Redd",       "year": "2005-06"},
            {"name": "Lamar Odom",         "year": "2005-06"},
            {"name": "Robert Parish",      "year": "1980-81"},
        ],
    },
    64: {
        "team": "Syracuse",
        "players": [
            {"name": "Tyrese Haliburton", "year": "2023-24"},
            {"name": "Sidney Moncrief",    "year": "1982-83"},
            {"name": "Tayshaun Prince",    "year": "2004-05"},
            {"name": "Dirk Nowitzki",      "year": "2010-11"},
            {"name": "Karl Malone",        "year": "1997-98"},
            {"name": "Baron Davis",        "year": "2006-07"},
            {"name": "Kirk Hinrich",       "year": "2006-07"},
            {"name": "Nicolas Batum",      "year": "2013-14"},
            {"name": "Boris Diaw",         "year": "2005-06"},
            {"name": "Vlade Divac",        "year": "1994-95"},
        ],
    },
    65: {
        "team": "Knicks",
        "players": [
            {"name": "Jason Kidd",         "year": "2002-03"},
            {"name": "Kobe Bryant",        "year": "2007-08"},
            {"name": "Kawhi Leonard",      "year": "2018-19"},
            {"name": "Charles Barkley",    "year": "1989-90"},
            {"name": "Dave Cowens",        "year": "1974-75"},
            {"name": "George Hill",        "year": "2016-17"},
            {"name": "Hal Greer",          "year": "1967-68"},
            {"name": "Elgin Baylor",       "year": "1961-62"},
            {"name": "Jaren Jackson Jr.",  "year": "2022-23"},
            {"name": "Al Horford",         "year": "2017-18"},
        ],
    },
    "65-D2": {
        "team": "OKST",
        "players": [
            {"name": "James Harden",       "year": "2020-21"},
            {"name": "Jerry West",         "year": "1967-68"},
            {"name": "Rick Barry",         "year": "1974-75"},
            {"name": "Bob McAdoo",         "year": "1974-75"},
            {"name": "Bill Russell",       "year": "1961-62"},
            {"name": "Deron Williams",     "year": "2009-10"},
            {"name": "Hal Greer",          "year": "1967-68"},
            {"name": "Ron Artest",         "year": "2003-04"},
            {"name": "Chris Webber",       "year": "1996-97"},
            {"name": "Nate Thurmond",      "year": "1968-69"},
        ],
    },
    66: {
        "team": "Boston College",
        "players": [
            {"name": "Allen Iverson",      "year": "2000-01"},
            {"name": "Jrue Holiday",       "year": "2021-22"},
            {"name": "Marques Johnson",    "year": "1980-81"},
            {"name": "Kevin Durant",       "year": "2016-17"},
            {"name": "Chris Bosh",         "year": "2012-13"},
            {"name": "Goran Dragic",       "year": "2013-14"},
            {"name": "Bobby Phills",       "year": "1995-96"},
            {"name": "James Worthy",       "year": "1986-87"},
            {"name": "Dave DeBusschere",   "year": "1969-70"},
            {"name": "Dikembe Mutombo",    "year": "1996-97"},
        ],
    },
    67: {
        "team": "Purdue",
        "players": [
            {"name": "Oscar Robertson",    "year": "1963-64"},
            {"name": "Dan Majerle",        "year": "1992-93"},
            {"name": "Andre Iguodala",     "year": "2011-12"},
            {"name": "Rashard Lewis",      "year": "2008-09"},
            {"name": "Shaquille O'Neal",   "year": "1999-00"},
            {"name": "Tiny Archibald",     "year": "1972-73"},
            {"name": "Byron Scott",        "year": "1987-88"},
            {"name": "Lou Hudson",         "year": "1969-70"},
            {"name": "Paul Millsap",       "year": "2014-15"},
            {"name": "Antonio McDyess",    "year": "1997-98"},
        ],
    },
    68: {
        "team": "Raptors",
        "players": [
            {"name": "Mike Conley",        "year": "2016-17"},
            {"name": "Michael Jordan",     "year": "1990-91"},
            {"name": "Marques Johnson",    "year": "1980-81"},
            {"name": "Kevin Love",         "year": "2013-14"},
            {"name": "Dwight Howard",      "year": "2010-11"},
            {"name": "George Hill",        "year": "2016-17"},
            {"name": "JJ Redick",          "year": "2015-16"},
            {"name": "Richard Jefferson",  "year": "2003-04"},
            {"name": "Tayshaun Prince",    "year": "2005-06"},
            {"name": "Sam Lacey",          "year": "1978-79"},
        ],
    },
    69: {
        "team": "Raptors",
        "players": [
            {"name": "Jeff Hornacek",      "year": "1991-92"},
            {"name": "Shai Gilgeous-Alexander","year": "2023-24"},
            {"name": "Gordon Hayward",     "year": "2016-17"},
            {"name": "Larry Nance Sr.",    "year": "1991-92"},
            {"name": "Wilt Chamberlain",   "year": "1966-67"},
            {"name": "George Hill",        "year": "2016-17"},
            {"name": "Paul Westphal",      "year": "1978-79"},
            {"name": "Billy Cunningham",   "year": "1969-70"},
            {"name": "Tayshaun Prince",    "year": "2005-06"},
            {"name": "Vlade Divac",        "year": "1994-95"},
        ],
    },
    71: {
        "team": "Houston",
        "players": [
            {"name": "Terry Porter",       "year": "1990-91"},
            {"name": "Brandon Roy",        "year": "2008-09"},
            {"name": "Ron Artest",         "year": "2003-04"},
            {"name": "Peja Stojaković",    "year": "2003-04"},
            {"name": "Joel Embiid",        "year": "2023-24"},
            {"name": "Baron Davis",        "year": "2006-07"},
            {"name": "Phil Smith",         "year": "1975-76"},
            {"name": "Bob Dandridge",      "year": "1978-79"},
            {"name": "Gus Johnson",        "year": "1968-69"},
            {"name": "Bob Pettit",         "year": "1958-59"},
        ],
    },
    72: {
        "team": "Grizzlies",
        "players": [
            {"name": "Gilbert Arenas",     "year": "2005-06"},
            {"name": "Jimmy Butler",       "year": "2016-17"},
            {"name": "Willie Wise",        "year": "1972-73"},
            {"name": "Larry Bird",         "year": "1985-86"},
            {"name": "Bam Adebayo",        "year": "2023-24"},
            {"name": "Isaiah Thomas",      "year": "2016-17"},
            {"name": "Latrell Sprewell",   "year": "1993-94"},
            {"name": "Mitch Richmond",     "year": "1996-97"},
            {"name": "Terry Cummings",     "year": "1984-85"},
            {"name": "Wes Unseld",         "year": "1974-75"},
        ],
    },
    73: {
        "team": "🧠",
        "players": [
            {"name": "Derek Harper",       "year": "1986-87"},
            {"name": "Penny Hardaway",     "year": "1995-96"},
            {"name": "Danny Green",        "year": "2014-15"},
            {"name": "Anthony Davis",      "year": "2019-20"},
            {"name": "Moses Malone",       "year": "1982-83"},
            {"name": "Fred Brown",         "year": "1975-76"},
            {"name": "Chet Walker",        "year": "1971-72"},
            {"name": "Gerald Wallace",     "year": "2009-10"},
            {"name": "Carmelo Anthony",    "year": "2008-09"},
            {"name": "PJ Brown",           "year": "2000-01"},
        ],
    },
    74: {
        "team": "Heat",
        "players": [
            {"name": "Gilbert Arenas",     "year": "2005-06"},
            {"name": "Sidney Moncrief",    "year": "1982-83"},
            {"name": "Magic Johnson",      "year": "1985-86"},
            {"name": "Chris Bosh",         "year": "2012-13"},
            {"name": "Moses Malone",       "year": "1982-83"},
            {"name": "JJ Redick",          "year": "2015-16"},
            {"name": "Brent Barry",        "year": "1999-00"},
            {"name": "Shane Battier",      "year": "2004-05"},
            {"name": "Bob Love",           "year": "1972-73"},
            {"name": "Ralph Sampson",      "year": "1984-85"},
        ],
    },
    75: {
        "team": "Mavericks",
        "players": [
            {"name": "Walt Frazier",       "year": "1971-72"},
            {"name": "Richard Hamilton",   "year": "2007-08"},
            {"name": "Paul Pierce",        "year": "2007-08"},
            {"name": "Lauri Markkanen",    "year": "2022-23"},
            {"name": "Bill Walton",        "year": "1976-77"},
            {"name": "Tiny Archibald",     "year": "1972-73"},
            {"name": "Kirk Hinrich",       "year": "2006-07"},
            {"name": "Elgin Baylor",       "year": "1960-61"},
            {"name": "Sam Perkins",        "year": "1994-95"},
            {"name": "Clifford Ray",       "year": "1973-74"},
        ],
    },
    76: {
        "team": "Mauritius",
        "players": [
            {"name": "Allen Iverson",      "year": "2000-01"},
            {"name": "Eddie Jones",        "year": "1999-00"},
            {"name": "LeBron James",       "year": "2012-13"},
            {"name": "Dirk Nowitzki",      "year": "2010-11"},
            {"name": "Chris Bosh",         "year": "2012-13"},
            {"name": "George Hill",        "year": "2016-17"},
            {"name": "Lou Hudson",         "year": "1969-70"},
            {"name": "Josh Howard",        "year": "2006-07"},
            {"name": "Jamaal Wilkes",      "year": "1979-80"},
            {"name": "Joakim Noah",        "year": "2013-14"},
        ],
    },
    77: {
        "team": "Estonia",
        "players": [
            {"name": "Terrell Brandon",    "year": "1995-96"},
            {"name": "Michael Jordan",     "year": "1990-91"},
            {"name": "Brandon Roy",        "year": "2008-09"},
            {"name": "Chris Bosh",         "year": "2012-13"},
            {"name": "Alonzo Mourning",    "year": "1999-00"},
            {"name": "George Hill",        "year": "2016-17"},
            {"name": "Allan Houston",      "year": "1999-00"},
            {"name": "Greg Ballard",       "year": "1981-82"},
            {"name": "Josh Smith",         "year": "2009-10"},
            {"name": "Alvan Adams",        "year": "1975-76"},
        ],
    },
    78: {
        "team": "Raptors",
        "players": [
            {"name": "Kevin Johnson",      "year": "1990-91"},
            {"name": "Walter Davis",       "year": "1978-79"},
            {"name": "Scottie Pippen",     "year": "1993-94"},
            {"name": "Rasheed Wallace",    "year": "2001-02"},
            {"name": "David Robinson",     "year": "1994-95"},
            {"name": "Isaiah Thomas",      "year": "2016-17"},
            {"name": "Dennis Johnson",     "year": "1981-82"},
            {"name": "Gary Harris",        "year": "2017-18"},
            {"name": "Carmelo Anthony",    "year": "2012-13"},
            {"name": "Brad Daugherty",     "year": "1991-92"},
        ],
    },
    79: {
        "team": "UCSC Banana Slugs",
        "players": [
            {"name": "Derek Harper",       "year": "1986-87"},
            {"name": "Jaylen Brown",       "year": "2023-24"},
            {"name": "Jayson Tatum",       "year": "2022-23"},
            {"name": "LeBron James",       "year": "2012-13"},
            {"name": "Al Horford",         "year": "2017-18"},
            {"name": "Baron Davis",        "year": "2006-07"},
            {"name": "Wesley Matthews",    "year": "2014-15"},
            {"name": "Joe Johnson",        "year": "2007-08"},
            {"name": "Sam Perkins",        "year": "1990-91"},
            {"name": "Artis Gilmore",      "year": "1974-75"},
        ],
    },
    80: {
        "team": "Arkansas Razorbacks",
        "players": [
            {"name": "Oscar Robertson",    "year": "1970-71"},
            {"name": "Danny Green",        "year": "2014-15"},
            {"name": "Khris Middleton",    "year": "2019-20"},
            {"name": "Kevin Garnett",      "year": "2007-08"},
            {"name": "Joel Embiid",        "year": "2023-24"},
            {"name": "Darius Garland",     "year": "2022-23"},
            {"name": "George Hill",        "year": "2016-17"},
            {"name": "George Gervin",      "year": "1973-74"},
            {"name": "Elgin Baylor",       "year": "1960-61"},
            {"name": "Billy Cunningham",   "year": "1969-70"},
        ],
    },
    81: {
        "team": "Denver Nuggets",
        "players": [
            {"name": "Jason Kidd",         "year": "2002-03"},
            {"name": "Mitch Richmond",     "year": "1996-97"},
            {"name": "Kevin Durant",       "year": "2016-17"},
            {"name": "Kevin Garnett",      "year": "2003-04"},
            {"name": "Dwight Howard",      "year": "2010-11"},
            {"name": "De'Aaron Fox",       "year": "2023-24"},
            {"name": "Kerry Kittles",      "year": "2002-03"},
            {"name": "Willie Wise",        "year": "1971-72"},
            {"name": "Connie Hawkins",     "year": "1969-70"},
            {"name": "Elton Brand",        "year": "2005-06"},
        ],
    },
    82: {
        "team": "Phoenix Suns",
        "players": [
            {"name": "Ja Morant",          "year": "2021-22"},
            {"name": "Brian Taylor",       "year": "1975-76"},
            {"name": "Jimmy Butler",       "year": "2020-21"},
            {"name": "Rasheed Wallace",    "year": "2001-02"},
            {"name": "Shaquille O'Neal",   "year": "1999-00"},
            {"name": "Jim Paxson",         "year": "1983-84"},
            {"name": "Tom Gola",           "year": "1959-60"},
            {"name": "Scott Wedman",       "year": "1978-79"},
            {"name": "Detlef Schrempf",    "year": "1994-95"},
            {"name": "Mychal Thompson",    "year": "1983-84"},
        ],
    },
    83: {
        "team": "Denver Nuggets",
        "players": [
            {"name": "Russell Westbrook",  "year": "2016-17"},
            {"name": "Jalen Williams",     "year": "2024-25"},
            {"name": "Chet Walker",        "year": "1971-72"},
            {"name": "Bobby Jones",        "year": "1976-77"},
            {"name": "Shaquille O'Neal",   "year": "1999-00"},
            {"name": "Kirk Hinrich",       "year": "2006-07"},
            {"name": "Paul Westphal",      "year": "1978-79"},
            {"name": "Steve Smith",        "year": "1997-98"},
            {"name": "Larry Kenon",        "year": "1978-79"},
            {"name": "Ralph Sampson",      "year": "1985-86"},
        ],
    },
    84: {
        "team": "Utah Jazz",
        "players": [
            {"name": "Trae Young",         "year": "2021-22"},
            {"name": "Kobe Bryant",        "year": "2007-08"},
            {"name": "Chris Mullin",       "year": "1990-91"},
            {"name": "Horace Grant",       "year": "1991-92"},
            {"name": "Karl Malone",        "year": "1997-98"},
            {"name": "Mike Bibby",         "year": "2004-05"},
            {"name": "Bobby Phills",       "year": "1995-96"},
            {"name": "Richard Jefferson",  "year": "2005-06"},
            {"name": "Jaden McDaniels",    "year": "2024-25"},
            {"name": "Andrew Bogut",       "year": "2009-10"},
        ],
    },
    85: {
        "team": "Buffalo Bills",
        "players": [
            {"name": "Russell Westbrook",  "year": "2016-17"},
            {"name": "Byron Scott",        "year": "1987-88"},
            {"name": "Kawhi Leonard",      "year": "2016-17"},
            {"name": "Chris Bosh",         "year": "2012-13"},
            {"name": "Moses Malone",       "year": "1982-83"},
            {"name": "Tiny Archibald",     "year": "1972-73"},
            {"name": "Jon McGlocklin",     "year": "1970-71"},
            {"name": "Jamal Mashburn",     "year": "2002-03"},
            {"name": "Boris Diaw",         "year": "2005-06"},
            {"name": "Dennis Rodman",      "year": "1991-92"},
        ],
    },
    86: {
        "team": "Washington Wizards",
        "players": [
            {"name": "Derrick Rose",       "year": "2010-11"},
            {"name": "Paul George",        "year": "2018-19"},
            {"name": "Danny Granger",      "year": "2008-09"},
            {"name": "Rasheed Wallace",    "year": "2001-02"},
            {"name": "Kevin Garnett",      "year": "2003-04"},
            {"name": "Sleepy Floyd",       "year": "1986-87"},
            {"name": "Dick Van Arsdale",   "year": "1969-70"},
            {"name": "Jamal Mashburn",     "year": "1999-00"},
            {"name": "Jerry Lucas",        "year": "1971-72"},
            {"name": "Arvydas Sabonis",    "year": "1997-98"},
        ],
    },
    87: {
        "team": "Ghana",
        "players": [
            {"name": "Mike Conley",        "year": "2016-17"},
            {"name": "Vince Carter",       "year": "2000-01"},
            {"name": "Ron Artest",         "year": "2003-04"},
            {"name": "LeBron James",       "year": "2012-13"},
            {"name": "Bob Lanier",         "year": "1973-74"},
            {"name": "Jamal Murray",       "year": "2022-23"},
            {"name": "Phil Chenier",       "year": "1975-76"},
            {"name": "Jason Richardson",   "year": "2005-06"},
            {"name": "Clifford Robinson",  "year": "1994-95"},
            {"name": "Ralph Sampson",      "year": "1984-85"},
        ],
    },
    88: {
        "team": "Brooklyn Nets",
        "players": [
            {"name": "Gilbert Arenas",     "year": "2005-06"},
            {"name": "Victor Oladipo",     "year": "2017-18"},
            {"name": "Jimmy Butler",       "year": "2020-21"},
            {"name": "Kevin McHale",       "year": "1985-86"},
            {"name": "Joakim Noah",        "year": "2013-14"},
            {"name": "Terrell Brandon",    "year": "1995-96"},
            {"name": "Mike Miller",        "year": "2006-07"},
            {"name": "Michael Finley",     "year": "2002-03"},
            {"name": "Clifford Robinson",  "year": "1999-00"},
            {"name": "Brad Miller",        "year": "2003-04"},
        ],
    },
    89: {
        "team": "Jacksonville Jaguars",
        "players": [
            {"name": "Stephen Curry",      "year": "2015-16"},
            {"name": "Gary Payton",        "year": "1997-98"},
            {"name": "Paul Pierce",        "year": "2007-08"},
            {"name": "James Worthy",       "year": "1986-87"},
            {"name": "Jack Sikma",         "year": "1981-82"},
            {"name": "Jason Terry",        "year": "2006-07"},
            {"name": "Ron Harper",         "year": "1988-89"},
            {"name": "Hedo Turkoglu",      "year": "2007-08"},
            {"name": "Richard Jefferson",  "year": "2003-04"},
            {"name": "Andrew Bogut",       "year": "2009-10"},
        ],
    },
    90: {
        "team": "Denver Nuggets",
        "players": [
            {"name": "Kevin Johnson",          "year": "1990-91"},
            {"name": "Kawhi Leonard",          "year": "2016-17"},
            {"name": "Bob Dandridge",          "year": "1978-79"},
            {"name": "Giannis Antetokounmpo",  "year": "2021-22"},
            {"name": "Dave Cowens",            "year": "1974-75"},
            {"name": "Michael Ray Richardson", "year": "1984-85"},
            {"name": "Donovan Mitchell",       "year": "2023-24"},
            {"name": "Willie Wise",            "year": "1972-73"},
            {"name": "Bob Pettit",             "year": "1962-63"},
            {"name": "Brook Lopez",            "year": "2022-23"},
        ],
    },
    91: {
        "team": "Charlotte Hornets",
        "players": [
            {"name": "Jason Kidd",         "year": "2002-03"},
            {"name": "Gilbert Arenas",     "year": "2005-06"},
            {"name": "Julius Erving",      "year": "1974-75"},
            {"name": "Scottie Pippen",     "year": "1993-94"},
            {"name": "Bill Russell",       "year": "1961-62"},
            {"name": "Fred Brown",         "year": "1975-76"},
            {"name": "Reggie Lewis",       "year": "1991-92"},
            {"name": "Detlef Schrempf",    "year": "1994-95"},
            {"name": "Blake Griffin",      "year": "2013-14"},
            {"name": "Vlade Divac",        "year": "1994-95"},
        ],
    },
    92: {
        "team": "Tampa Bay Buccaneers",
        "players": [
            {"name": "Stephen Curry",      "year": "2015-16"},
            {"name": "James Harden",       "year": "2019-20"},
            {"name": "Scott Wedman",       "year": "1978-79"},
            {"name": "Larry Nance Sr.",    "year": "1988-89"},
            {"name": "Bam Adebayo",        "year": "2023-24"},
            {"name": "Darrell Armstrong",  "year": "1998-99"},
            {"name": "Randy Smith",        "year": "1975-76"},
            {"name": "Franz Wagner",       "year": "2024-25"},
            {"name": "Toni Kukoc",         "year": "1995-96"},
            {"name": "Isaiah Hartenstein", "year": "2024-25"},
        ],
    },
    93: {
        "teams": [
            {
                "team": "Tennessee Titans",
                "players": [
                    {"name": "Baron Davis",        "year": "2006-07"},
                    {"name": "Manu Ginóbili",      "year": "2007-08"},
                    {"name": "Jalen Williams",     "year": "2024-25"},
                    {"name": "Peja Stojaković",    "year": "2003-04"},
                    {"name": "Hakeem Olajuwon",    "year": "1993-94"},
                    {"name": "Isaiah Thomas",      "year": "2016-17"},
                    {"name": "Gary Harris",        "year": "2017-18"},
                    {"name": "Latrell Sprewell",   "year": "1993-94"},
                    {"name": "David West",         "year": "2012-13"},
                    {"name": "Yao Ming",           "year": "2005-06"},
                ],
            },
            {
                "team": "Las Vegas Raiders",
                "players": [
                    {"name": "Gilbert Arenas",     "year": "2005-06"},
                    {"name": "Jerry West",         "year": "1967-68"},
                    {"name": "Dan Majerle",        "year": "1992-93"},
                    {"name": "Rashard Lewis",      "year": "2008-09"},
                    {"name": "Dwight Howard",      "year": "2010-11"},
                    {"name": "De'Aaron Fox",       "year": "2022-23"},
                    {"name": "Jon McGlocklin",     "year": "1970-71"},
                    {"name": "Billy Cunningham",   "year": "1969-70"},
                    {"name": "Hedo Turkoglu",      "year": "2007-08"},
                    {"name": "Jermaine O'Neal",    "year": "2003-04"},
                ],
            },
            {
                "team": "New York Knicks",
                "players": [
                    {"name": "Derrick White",      "year": "2023-24"},
                    {"name": "Devin Booker",       "year": "2022-23"},
                    {"name": "Alex English",       "year": "1982-83"},
                    {"name": "Draymond Green",     "year": "2015-16"},
                    {"name": "David Robinson",     "year": "1994-95"},
                    {"name": "John Wall",          "year": "2016-17"},
                    {"name": "Jason Richardson",   "year": "2005-06"},
                    {"name": "Scott Wedman",       "year": "1978-79"},
                    {"name": "Buck Williams",      "year": "1982-83"},
                    {"name": "Amar'e Stoudemire",  "year": "2004-05"},
                ],
            },
            {
                "team": "Brooklyn Nets",
                "players": [
                    {"name": "Isiah Thomas",       "year": "1984-85"},
                    {"name": "Desmond Bane",       "year": "2023-24"},
                    {"name": "John Havlicek",      "year": "1971-72"},
                    {"name": "Shawn Marion",       "year": "2005-06"},
                    {"name": "Kareem Abdul-Jabbar","year": "1976-77"},
                    {"name": "Trae Young",         "year": "2021-22"},
                    {"name": "Byron Scott",        "year": "1987-88"},
                    {"name": "Mike Miller",        "year": "2006-07"},
                    {"name": "Kiki Vandeweghe",    "year": "1983-84"},
                    {"name": "Ben Wallace",        "year": "2003-04"},
                ],
            },
            {
                "team": "San Diego Rockets",
                "players": [
                    {"name": "Cade Cunningham",    "year": "2024-25"},
                    {"name": "Reggie Miller",      "year": "1993-94"},
                    {"name": "Tracy McGrady",      "year": "2002-03"},
                    {"name": "Rasheed Wallace",    "year": "2003-04"},
                    {"name": "Bam Adebayo",        "year": "2022-23"},
                    {"name": "Terrell Brandon",    "year": "1995-96"},
                    {"name": "Allan Houston",      "year": "1999-00"},
                    {"name": "Amen Thompson",      "year": "2024-25"},
                    {"name": "Robert Horry",       "year": "1995-96"},
                    {"name": "Ivica Zubac",        "year": "2024-25"},
                ],
            },
        ],
    },
    94: {
        "team": "Chicago Bulls",
        "players": [
            {"name": "Tracy McGrady",      "year": "2002-03"},
            {"name": "Derrick White",      "year": "2023-24"},
            {"name": "Bob Dandridge",      "year": "1978-79"},
            {"name": "Hedo Turkoglu",      "year": "2007-08"},
            {"name": "Hakeem Olajuwon",    "year": "1993-94"},
            {"name": "Sam Cassell",        "year": "2003-04"},
            {"name": "Fred VanVleet",      "year": "2021-22"},
            {"name": "Gerald Wallace",     "year": "2009-10"},
            {"name": "Robert Horry",       "year": "1995-96"},
            {"name": "Ralph Sampson",      "year": "1984-85"},
        ],
    },
    95: {
        "team": "Vancouver Grizzlies",
        "players": [
            {"name": "Chris Paul",         "year": "2014-15"},
            {"name": "Manu Ginóbili",      "year": "2007-08"},
            {"name": "Michael Finley",     "year": "2002-03"},
            {"name": "Blake Griffin",      "year": "2013-14"},
            {"name": "Patrick Ewing",      "year": "1989-90"},
            {"name": "Gus Williams",       "year": "1981-82"},
            {"name": "David Thompson",     "year": "1977-78"},
            {"name": "Carmelo Anthony",    "year": "2012-13"},
            {"name": "Dave DeBusschere",   "year": "1969-70"},
            {"name": "Robert Parish",      "year": "1981-82"},
        ],
    },
    96: {
        "team": "Arsenal FC",
        "players": [
            {"name": "Tyrese Haliburton", "year": "2024-25"},
            {"name": "Wesley Matthews",    "year": "2014-15"},
            {"name": "Julius Erving",      "year": "1975-76"},
            {"name": "Larry Bird",         "year": "1985-86"},
            {"name": "Patrick Ewing",      "year": "1989-90"},
            {"name": "Sleepy Floyd",       "year": "1986-87"},
            {"name": "Danny Ainge",        "year": "1987-88"},
            {"name": "Michael Redd",       "year": "2005-06"},
            {"name": "Tayshaun Prince",    "year": "2004-05"},
            {"name": "Ivica Zubac",        "year": "2024-25"},
        ],
    },
    97: {
        "team": "Marquette Golden Eagles",
        "players": [
            {"name": "Tyrese Haliburton",      "year": "2024-25"},
            {"name": "Reggie Miller",          "year": "1993-94"},
            {"name": "Shane Battier",          "year": "2006-07"},
            {"name": "Giannis Antetokounmpo",  "year": "2021-22"},
            {"name": "Rudy Gobert",            "year": "2020-21"},
            {"name": "Tyrese Maxey",           "year": "2024-25"},
            {"name": "Phil Chenier",           "year": "1974-75"},
            {"name": "Franz Wagner",           "year": "2024-25"},
            {"name": "Kevin Love",             "year": "2013-14"},
            {"name": "Bill Laimbeer",          "year": "1988-89"},
        ],
    },
    98: {
        "team": "UNC Tar Heels",
        "players": [
            {"name": "Shai Gilgeous-Alexander","year": "2024-25"},
            {"name": "Manu Ginóbili",          "year": "2004-05"},
            {"name": "Latrell Sprewell",       "year": "1993-94"},
            {"name": "Evan Mobley",            "year": "2024-25"},
            {"name": "Victor Wembanyama",      "year": "2024-25"},
            {"name": "De'Aaron Fox",           "year": "2022-23"},
            {"name": "Gary Harris",            "year": "2017-18"},
            {"name": "Jamaal Wilkes",          "year": "1979-80"},
            {"name": "Sam Perkins",            "year": "1994-95"},
            {"name": "Isaiah Hartenstein",     "year": "2024-25"},
        ],
    },
    99: {
        "team": "Cincinnati Royals",
        "players": [
            {"name": "Kevin Johnson",      "year": "1990-91"},
            {"name": "Danny Green",        "year": "2014-15"},
            {"name": "Rick Barry",         "year": "1974-75"},
            {"name": "Chris Bosh",         "year": "2012-13"},
            {"name": "Kareem Abdul-Jabbar","year": "1973-74"},
            {"name": "Jamal Murray",       "year": "2022-23"},
            {"name": "Phil Smith",         "year": "1975-76"},
            {"name": "Tayshaun Prince",    "year": "2005-06"},
            {"name": "LaMarcus Aldridge",  "year": "2017-18"},
            {"name": "Arvydas Sabonis",    "year": "1997-98"},
        ],
    },
    100: {
        "team": "UCF Knights",
        "players": [
            {"name": "Tracy McGrady",          "year": "2002-03"},
            {"name": "Klay Thompson",          "year": "2015-16"},
            {"name": "Bob Dandridge",          "year": "1978-79"},
            {"name": "Giannis Antetokounmpo",  "year": "2021-22"},
            {"name": "Pau Gasol",              "year": "2008-09"},
            {"name": "Darius Garland",         "year": "2022-23"},
            {"name": "Jalen Rose",             "year": "1999-00"},
            {"name": "Michael Finley",         "year": "2002-03"},
            {"name": "Dan Roundfield",         "year": "1979-80"},
            {"name": "Brook Lopez",            "year": "2022-23"},
        ],
    },
    101: {
        "team": "Iowa Hawkeyes",
        "players": [
            {"name": "Derek Harper",       "year": "1986-87"},
            {"name": "Brandon Roy",        "year": "2008-09"},
            {"name": "Paul Pierce",        "year": "2007-08"},
            {"name": "Connie Hawkins",     "year": "1968-69"},
            {"name": "Hakeem Olajuwon",    "year": "1993-94"},
            {"name": "Paul Westphal",      "year": "1978-79"},
            {"name": "Zach LaVine",        "year": "2020-21"},
            {"name": "Josh Howard",        "year": "2006-07"},
            {"name": "Robert Covington",   "year": "2017-18"},
            {"name": "Yao Ming",           "year": "2007-08"},
        ],
    },
    102: {
        "team": "Portland Trail Blazers",
        "players": [
            {"name": "Jason Kidd",             "year": "2002-03"},
            {"name": "Kyrie Irving",           "year": "2020-21"},
            {"name": "Andre Iguodala",         "year": "2011-12"},
            {"name": "Giannis Antetokounmpo",  "year": "2021-22"},
            {"name": "Karl-Anthony Towns",     "year": "2024-25"},
            {"name": "Kirk Hinrich",           "year": "2006-07"},
            {"name": "Bobby Phills",           "year": "1995-96"},
            {"name": "Jamaal Wilkes",          "year": "1979-80"},
            {"name": "Clifford Robinson",      "year": "1999-00"},
            {"name": "Tyson Chandler",         "year": "2011-12"},
        ],
    },
    103: {
        "team": "Tulane Green Wave",
        "players": [
            {"name": "Russell Westbrook",  "year": "2016-17"},
            {"name": "Ray Allen",          "year": "2000-01"},
            {"name": "Shane Battier",      "year": "2006-07"},
            {"name": "Larry Bird",         "year": "1983-84"},
            {"name": "Alonzo Mourning",    "year": "1999-00"},
            {"name": "Danny Ainge",        "year": "1987-88"},
            {"name": "Reggie Lewis",       "year": "1992-93"},
            {"name": "Roger Brown",        "year": "1968-69"},
            {"name": "Robert Horry",       "year": "1995-96"},
            {"name": "Nate Thurmond",      "year": "1968-69"},
        ],
    },
    104: {
        "team": "New Orleans Hornets",
        "players": [
            {"name": "Gary Payton",        "year": "1997-98"},
            {"name": "Sidney Moncrief",    "year": "1983-84"},
            {"name": "Elgin Baylor",       "year": "1961-62"},
            {"name": "Larry Bird",         "year": "1985-86"},
            {"name": "Al Horford",         "year": "2017-18"},
            {"name": "Goran Dragic",       "year": "2013-14"},
            {"name": "Dale Ellis",         "year": "1988-89"},
            {"name": "Jerome Kersey",      "year": "1990-91"},
            {"name": "Clifford Robinson",  "year": "1999-00"},
            {"name": "Andrew Bogut",       "year": "2009-10"},
        ],
    },
}
