# emoji_map.py
# Maps Discord custom emoji names → team names exactly as they appear in the Google Sheet.
#
# HOW TO FIND AN EMOJI'S NAME:
#   In Discord, type a backslash before the emoji: \:YourEmoji:
#   Discord will show you the full text like <:MilwaukeeBucks:1234567890>
#   The name is the part between the colons → "MilwaukeeBucks"
#
# IMPORTANT: The team name on the right must match EXACTLY what's in row 1
#            of that team's section in your Google Sheet (including capitalisation).
#
# FORMAT:
#   "EmojiName": "Team Name In Sheet",

EMOJI_TEAM_MAP = {
    # ── Add your teams below
    "San_Antonio_Spurs": "San Antonio Spurs",
    "SAS": "San Antonio Spurs",
    "Spurs": "San Antonio Spurs",
    "Spurs~1": "San Antonio Spurs",
    "Milwaukee_Bucks": "Milwaukee Bucks",
    "Warriors": "Golden State Warriors",
    "Pacers": "Indiana Pacers",
    "Lakers": "Los Angeles Lakers",
    "Heat": "Miami Heat",
    "Heat2": "Miami Heat",
    "MIA": "Miami Heat",
    "Raptors": "Toronto Raptors",
    "Wizards": "Washington Wizards",
    "Magic": "Orlando Magic",
    "Hornets": "New Orleans Hornets",
    "PSR": "Providence Steamrollers",
    "Cavs": "Cleveland Cavaliers",
    "Celtics": "Boston Celtics",
    "Clippers": "Los Angeles Clippers",
    "CornellBigRed": "Cornell Big Red",
    "Duke": "Duke Blue Devils",
    "Gonzaga": "Gonzaga Bulldogs",
    "Kentucky": "Kentucky Wildcats",
    "Kansas": "Kansas Jayhawks",
    "Northwestern": "Northwestern Wildcats",
    "Sonics": "Seattle SuperSonics",
    "OKC": "Oklahoma City Thunder",
    "UNC": "North Carolina Tar Heels",
    "Pelicans": "New Orleans Pelicans",
    "pelicans": "New Orleans Pelicans",
    "Nuggets": "Denver Nuggets",
    "nuggets": "Denver Nuggets",
    "Jazz": "Utah Jazz",
    "MichiganState": "Michigan State Spartans",
    "LSU": "LSU Tigers",
    "UCLA": "UCLA Bruins",
    "Uconn": "UConn Huskies",
    "TCU": "TCU Horned Frogs",
    "Iowa": "Iowa Hawkeyes",
    "Ohio": "Ohio State Buckeyes",
    "Purdue": "Purdue Boilermakers",
    "Marquette": "Marquette Golden Eagles",
    "Louisville": "Louisville Cardinals",
    "Washington_State_Cougars": "Washington State Cougars",
    "Orl2": "Orlando Magic",
    "UCSantaCruzBananaSlugs": "UCSC Banana Slugs",
    "Minn": "Minnesota Timberwolves",
    "MIN": "Minnesota Timberwolves",
    "Titans": "Tennessee Titans",
    "Browns": "Cleveland Browns",
    "Pacers": "Indiana Pacers",
    "Nets": "Brooklyn Nets",
    "Bulls": "Chicago Bulls",
    "Grizzlies": "Memphis Grizzlies",
    "MEM": "Memphis Grizzlies",
    "Rockets": "Houston Rockets",
    "Kings": "Sacramento Kings",
    "76ers": "Philadelphia 76ers",
    "Mavericks": "Dallas Mavericks",
    "mavs": "Dallas Mavericks",
    "Bucks": "Milwaukee Bucks",
    "MIL2": "Milwaukee Bucks",
    "Knicks": "New York Knicks",
    "Suns": "Phoenix Suns",
    "WashingtonHuskies": "Washington Huskies",
    "huskies": "Washington Huskies",
    "WashingtonHuskies~1": "Washington Huskies",
    "Piston": "Detroit Pistons",
    "pistons": "Detroit Pistons",
    "Syracuse": "Syracuse Orange",
    "Hoosiers": "Indiana Hoosiers",
    "Bobcats": "Charlotte Bobcats",
    "MichiganWolverines": "Michigan Wolverines",
    "DrakeBulldogs": "Drake Bulldogs",
    "OKST": "Oklahoma State Cowboys",
    "CreightonBulljays": "Creighton Bluejays",
    "CreightonBluejays": "Creighton Bluejays",
    "CalPoly:": "Cal Poly Mustangs",
    "CCSU:": "Ctr. Connecticut Blue Devils",
    "SIUE:": "SIU-Edwardsville Cougars",
    "arkansasrazorbacks": "Arkansas Razorbacks",
    "Celtics~1": "Boston Celtics",
    "heat": "Miami Heat",
    "heat2": "Miami Heat",        
    "Northwestern~1": "Northwestern Wildcats",
    "IOWncaa": "Iowa Hawkeyes",
    "NOH": "New Orleans Hornets",
    "NOH~1": "New Orleans Hornets",
    ":NOH~2:": "New Orleans Hornets",
    "Clippers~1": "Los Angeles Clippers",
    "MichiganWolverines~1": "Michigan Wolverines",
    "TOR2~1": "Toronto Huskies",
    "TOR2": "Toronto Huskies",
    "TulaneGreenWave~1": "Tulane Green Wave",
    "TulaneGreenWave": "Tulane Green Wave",
    "ravens": "Baltimore Ravens",
    "UConn": "UConn Huskies",
    "Knicks~1": "New York Knicks",
    "76ers_Old": "Philadelphia 76ers",
    "MIN~7": "Minnesota Timberwolves",
    "pistons~2": "Detroit Pistons",
    "0Clemson~2": "Clemson Tigers",
    "0Clemson": "Clemson Tigers",
    "ClemsonTigers": "Clemson Tigers",
    "SAS~5": "San Antonio Spurs",
    "titans": "Tennessee Titans",
    "nuggets~3": "Denver Nuggets",
    "ucf_knights": "UCF Knights",
    "miami": "Miami Hurricanes",
    "Maine_Black_Bears": "Maine Black Bears",
    "trailblazers": "Portland Trail Blazers",
    "rockets": "Houston Rockets",
    "VAN": "Vancouver Grizzlies",
    "Celtics2": "Boston Celtics",
    "CIN": "Cincinnati Royals",
    "BAL": "Baltimore Bullets",
    "SDR": "San Diego Rockets",
    "VIR": "Virginia Squires",
    "NYK": "New York Knicks",
    "CLE": "Cleveland Cavaliers",
    "NPC": "Newport",              
    "ORL": "Orlando Magic",
    "ORL2": "Orlando Magic",
    "IND": "Indiana Pacers",
    "DAL": "Dallas Mavericks",
    "POR": "Portland Trail Blazers",
    "PHI": "Philadelphia 76ers",
    "SAC": "Sacramento Kings",
    "CHI": "Chicago Bulls",
    "NOP": "New Orleans Pelicans",
    "UTA": "Utah Jazz",
    "MIL": "Milwaukee Bucks",
    "HOU": "Houston Rockets",
    "ATL": "Atlanta Hawks",
    "SMU": "SMU Mustangs",
    "CHA": "Charlotte Hornets",
    "PHO": "Phoenix Suns",
    "LAL": "Los Angeles Lakers",
    "BKN": "Brooklyn Nets",
    "BOS": "Boston Celtics",
    "DET": "Detroit Pistons",
    "DEN": "Denver Nuggets",
    "DUKE": "Duke Blue Devils",
    "GSW": "Golden State Warriors",
    "NW": "Northwestern Wildcats",
    "NJN": "New Jersey Nets",
    "TOR": "Toronto Raptors",
    "TOR~4": "Toronto Raptors",
    "Florida": "Florida Gators",
    "mpl": "Minneapolis Lakers",
    "southernmethodistuniversity": "SMU Mustangs",
    "LasVegasRaiders": "Las Vegas Raiders",
    "BYU": "BYU Cougars",
    "patriots": "New England Patriots",
    "dolphins": "Miami Dolphins",
    "Florida_Panthers": "Florida Panthers",
    "LARams2": "Los Angeles Rams",
    "seahawks": "Seattle Seahawks",
    "OGSuns": "Phoenix Suns",
    "MPL": "Minneapolis Lakers",
    "RealMadrid": "Real Madrid",
    "oregon": "Oregon Ducks",
    "Jets": "New York Jets",
    "alaskaanchorage": "Alaska Seawolves",
    "rams": "Los Angeles Rams",
    "vikings": "Minnesota Vikings",
    "texans": "Houston Texans",
    "Coastal_Carolina": "Carolina Chanticleers",
    "Wizards_Old": "Washington Wizards",
    "broncos": "Denver Broncos",
    "Harvard": "Harvard Crimson",
    "Wizards1": "Washington Wizards",
    "boise": "Boise State Broncos",
    "LiberalBeejays": "Liberal Beejays",
    "bucs": "Tampa Bay Buccaneers",
    "steelers": "Pittsburgh Steelers",
    "sixer": "Philadelphia 76ers",
    # ── lowercase / variant spellings ────────────────────────────────────────
    "milwaukee_bucks": "Milwaukee Bucks",
    "blazers":        "Portland Trail Blazers",
    "raptors":        "Toronto Raptors",
    "wizards":        "Washington Wizards",
    "browns":         "Cleveland Browns",
    "chargers":       "Los Angeles Chargers",
    "falcons":        "Atlanta Falcons",
    "Falcons":        "Atlanta Falcons",
    "bulls":          "Chicago Bulls",
    "jazz":           "Utah Jazz",
    "bucks":          "Milwaukee Bucks",
    "kings":          "Sacramento Kings",
    "pacers":         "Indiana Pacers",
    "suns":           "Phoenix Suns",
    "thunder":        "Oklahoma City Thunder",
    "grizzlies":      "Memphis Grizzlies",
    "knicks":         "New York Knicks",
    "Houston":        "Houston Rockets",
    "Vancouver":      "Vancouver Grizzlies",
    "real_madrid":    "Real Madrid",
    "Pistons":        "Detroit Pistons",
    "CHI3":           "Chicago Bulls",
    "nuggets~2":      "Denver Nuggets",
    "spurs~1":        "San Antonio Spurs",
    "Raptors2":       "Toronto Raptors",
    "Alabama":        "Alabama Crimson Tide",
    "OGsonics":       "Seattle SuperSonics",
    # ── additional ~N duplicate-name emoji variants ─────────────────────────────
    "76ers~3":                     "Philadelphia 76ers",
    "Lakers~1":                    "Los Angeles Lakers",
    "PSR~4":                       "Providence Steamrollers",
    "UCSantaCruzBananaSlugs~1":    "UCSC Banana Slugs",
    "blazers~1":                   "Portland Trail Blazers",
    "bucks~1":                     "Milwaukee Bucks",
    "bulls~1":                     "Chicago Bulls",
    "celtics~2":                   "Boston Celtics",
    "celtics~4":                   "Boston Celtics",
    "heat~4":                      "Miami Heat",
    "jazz~2":                      "Utah Jazz",
    "knicks~2":                    "New York Knicks",
    "lakers~3":                    "Los Angeles Lakers",
    "pelicans~3":                  "New Orleans Pelicans",
    "raptors~1":                   "Toronto Raptors",
    "rockets~4":                   "Houston Rockets",
    "rockets~5":                   "Houston Rockets",
    "spurs~3":                     "San Antonio Spurs",
    "suns~1":                      "Phoenix Suns",
    "thunder~1":                   "Oklahoma City Thunder",
    "trailblazers~4":              "Portland Trail Blazers",
    # ── new teams ─────────────────────────────────────────────────────────────
    "0Jaguars":                    "Jacksonville Jaguars",
    "jaguars":                     "Jacksonville Jaguars",
    "SYRncaa":                     "Syracuse Orange",
    "pennstatenittanylionslogo":   "Penn State Nittany Lions",
    "0Bills":                      "Buffalo Bills",
    "bills":                       "Buffalo Bills",
    "pistonslogo3":                "Detroit Pistons",
    "borussiaDortmund":            "Borussia Dortmund",
    "CaliforniaGoldenBearsLogo2004": "California Golden Bears",
    "lions":                       "Detroit Lions",
    "0Chargers":                   "Los Angeles Chargers",
    "hornets2":                    "Charlotte Hornets",
    "NYG":                         "New York Giants",
    "mariners":                    "Seattle Mariners",
    "TitansL":                     "Tennessee Titans",
    "TexasTech":                   "Texas Tech Red Raiders",
    "t_patriots":                  "New England Patriots",
    "Nebraska_Cornhuskers":        "Nebraska Cornhuskers",
    "Zalgirls":                    "Zalgiris",
    "bengals":                     "Cincinnati Bengals",
    "0Kentucky":                   "Kentucky Wildcats",
    "Arkansas_Razorbacks":         "Arkansas Razorbacks",
    "0Illinois":                   "Illinois Fighting Illini",
    "ConnecticutSun":              "Connecticut Sun",
    "ConnecticutSuns":             "Connecticut Sun",
    "t_broncos":                   "Denver Broncos",
    "beejays":                     "Liberal Beejays",
    "Beejays":                     "Liberal Beejays",
    "HaopelTelAviv":               "Hapoel Tel Aviv",
    "notredame2":                  "Notre Dame Fighting Irish",
    "Hawaii":                      "Hawaii Rainbow Warriors",
    "liberal_beejays":             "Liberal Beejays",
    "CarolinaPanthers":            "Carolina Panthers",
    "oneaboveall":                 "One Above All",
    "texas_am_aggies":             "Texas A&M Aggies",
    "WCU":                         "Western Carolina Catamounts",
    "saints":                      "New Orleans Saints",
    "heat~2":                      "Miami Heat",
    "0Yale":                       "Yale Bulldogs",
    "Buffalo_Braves":              "Buffalo Braves",
    "PIT2":                        "Pittsburgh Steelers",
    "eagles":                      "Philadelphia Eagles",
    "0Texans":                     "Houston Texans",
    "Celtics":                     "Boston Celtics",
    "76ers":                       "Philadelphia 76ers",
    "76ers_2":                     "Philadelphia 76ers",
    "BWB_Cleveland_Cavaliers":     "Cleveland Cavaliers",
    "SacrementoMonarchs":          "Sacramento Monarchs",
    "notredame":                   "Notre Dame Fighting Irish",
    "OGSpurs":                     "San Antonio Spurs",
    "MiamiHeatVice":               "Miami Heat",
    "Grizzlies2":                  "Memphis Grizzlies",
    "KentState":                   "Kent State Golden Flashes",
    "BostonCollegeEagles":         "Boston College Eagles",
    "Shanghai_Sharks":             "Shanghai Sharks",
    "HolyCrossCrusaders":          "Holy Cross Crusaders",
    "TexasTechRedRaiders":         "Texas Tech Red Raiders",
    "clippersnewlogo":             "Los Angeles Clippers",
    "Starzz":                      "Utah Starzz",
    "timberwolves":                "Minnesota Timberwolves",
    "Timberwolves":                "Minnesota Timberwolves",
    "ECU":                         "East Carolina Pirates",
    "rockets~2":                   "Houston Rockets",
    "Dallas_Chaparrals":           "Dallas Chaparrals",
    "Texas":                       "Texas Longhorns",
    "IdahoVandals":                "Idaho Vandals",
    "magic":                       "Orlando Magic",
    "mavericks":                   "Dallas Mavericks",
    "hornets":                     "New Orleans Hornets",
    "Hornets2":                    "Charlotte Hornets",
    "lsu":                         "LSU Tigers",
    "CHI2":                        "Chicago Bulls",
    "Lakers1":                     "Los Angeles Lakers",
    "UMKC":                        "UMKC Kangaroos",
    "Havard":                      "Harvard Crimson",
    "raptors2":                    "Toronto Raptors",
    "phoenix_suns":                "Phoenix Suns",
    # ── ATD 52–58 ────────────────────────────────────────────────────────────────
    "Rebels":           "Ole Miss Rebels",
    "Jackarbbit":       "South Dakota State Jackrabbits",
    "UBC":              "UBC Thunderbirds",
    "Pistons_Concept":  "Detroit Pistons",
    "OKCnba":           "Oklahoma City Thunder",
    "OGraptors":        "Toronto Raptors",
    "washington":       "Washington Wizards",
    "VAN~1": "Vancouver Grizzlies",
    "MIN~1": "Minnesota Timberwolves",
    "Sonics~1": "Seattle SuperSonics",
    "rockets~1": "Houston Rockets",
    "PSR~1": "Providence Steamrollers",
    "nuggets~1": "Denver Nuggets",
    "OKC~2": "Oklahoma City Thunder",
    "pelicans~1": "New Orleans Pelicans",
    "CIN~1": "Cincinnati Royals",
    "trailblazers~1": "Portland Trail Blazers",
    "Grizzlies~1": "Memphis Grizzlies",
    "SDR~1": "San Diego Rockets",
    "hawks": "Atlanta Hawks",
    "spurs": "San Antonio Spurs",
    "heat~1": "Miami Heat",
    "nets": "Brooklyn Nets",
    "Nets~1": "Brooklyn Nets",
    "sixers": "Philadelphia 76ers",
    "lakers": "Los Angeles Lakers",
    "cavs": "Cleveland Cavaliers",
    "celtics": "Boston Celtics",
    "chi3": "Chicago Bulls",
    "Patriots": "New England Patriots",
    "Nuggets": "Denver Nuggets",
}

# Unicode (built-in Discord) emojis → team names.
# Add flag/country emojis here.
UNICODE_EMOJI_MAP = {
    # ── UEFA (Europe) ─────────────────────────────────────────────────────────
    "🇦🇱": "Albania",
    "AL":  "Albania",
    "🇦🇩": "Andorra",
    "AD":  "Andorra",
    "🇦🇲": "Armenia",
    "AM":  "Armenia",
    "🇦🇹": "Austria",
    "AT":  "Austria",
    "🇦🇿": "Azerbaijan",
    "AZ":  "Azerbaijan",
    "🇧🇾": "Belarus",
    "BY":  "Belarus",
    "🇧🇪": "Belgium",
    "BE":  "Belgium",
    "🇧🇦": "Bosnia and Herzegovina",
    "BA":  "Bosnia and Herzegovina",
    "🇧🇬": "Bulgaria",
    "BG":  "Bulgaria",
    "🇭🇷": "Croatia",
    "HR":  "Croatia",
    "🇨🇾": "Cyprus",
    "CY":  "Cyprus",
    "🇨🇿": "Czech Republic",
    "CZ":  "Czech Republic",
    "🇩🇰": "Denmark",
    "DK":  "Denmark",
    "🇪🇪": "Estonia",
    "EE":  "Estonia",
    "🇫🇮": "Finland",
    "FI":  "Finland",
    "🇫🇷": "France",
    "FR":  "France",
    "🇬🇪": "Georgia",
    "GE":  "Georgia",
    "🇩🇪": "Germany",
    "DE":  "Germany",
    "🇬🇷": "Greece",
    "GR":  "Greece",
    "🇭🇺": "Hungary",
    "HU":  "Hungary",
    "🇮🇸": "Iceland",
    "IS":  "Iceland",
    "🇮🇪": "Ireland",
    "IE":  "Ireland",
    "🇮🇹": "Italy",
    "IT":  "Italy",
    "🇽🇰": "Kosovo",
    "XK":  "Kosovo",
    "🇱🇻": "Latvia",
    "LV":  "Latvia",
    "🇱🇮": "Liechtenstein",
    "LI":  "Liechtenstein",
    "🇱🇹": "Lithuania",
    "LT":  "Lithuania",
    "🇱🇺": "Luxembourg",
    "LU":  "Luxembourg",
    "🇲🇹": "Malta",
    "MT":  "Malta",
    "🇲🇩": "Moldova",
    "MD":  "Moldova",
    "🇲🇪": "Montenegro",
    "ME":  "Montenegro",
    "🇳🇱": "Netherlands",
    "NL":  "Netherlands",
    "🇲🇰": "North Macedonia",
    "MK":  "North Macedonia",
    "🇳🇴": "Norway",
    "NO":  "Norway",
    "🇵🇱": "Poland",
    "PL":  "Poland",
    "🇵🇹": "Portugal",
    "PT":  "Portugal",
    "🇷🇴": "Romania",
    "RO":  "Romania",
    "🇷🇺": "Russia",
    "RU":  "Russia",
    "🇸🇲": "San Marino",
    "SM":  "San Marino",
    "🇷🇸": "Serbia",
    "RS":  "Serbia",
    "🇸🇰": "Slovakia",
    "SK":  "Slovakia",
    "🇸🇮": "Slovenia",
    "SI":  "Slovenia",
    "🇪🇸": "Spain",
    "ES":  "Spain",
    "🇸🇪": "Sweden",
    "SE":  "Sweden",
    "🇨🇭": "Switzerland",
    "CH":  "Switzerland",
    "🇹🇷": "Turkey",
    "TR":  "Turkey",
    "🇺🇦": "Ukraine",
    "UA":  "Ukraine",
    "🇬🇧": "England",
    "GB":  "England",
    "🏴󠁧󠁢󠁥󠁮󠁧󠁿": "England",
    "🏴󠁧󠁢󠁳󠁣󠁴󠁿": "Scotland",
    "🏴󠁧󠁢󠁷󠁬󠁳󠁿": "Wales",
    # ── CONMEBOL (South America) ───────────────────────────────────────────────
    "🇦🇷": "Argentina",
    "AR":  "Argentina",
    "🇧🇴": "Bolivia",
    "BO":  "Bolivia",
    "🇧🇷": "Brazil",
    "BR":  "Brazil",
    "🇨🇱": "Chile",
    "CL":  "Chile",
    "🇨🇴": "Colombia",
    "CO":  "Colombia",
    "🇪🇨": "Ecuador",
    "EC":  "Ecuador",
    "🇵🇾": "Paraguay",
    "PY":  "Paraguay",
    "🇵🇪": "Peru",
    "PE":  "Peru",
    "🇺🇾": "Uruguay",
    "UY":  "Uruguay",
    "🇻🇪": "Venezuela",
    "VE":  "Venezuela",
    # ── CONCACAF (North/Central America & Caribbean) ──────────────────────────
    "🇧🇿": "Belize",
    "BZ":  "Belize",
    "🇨🇦": "Canada",
    "CA":  "Canada",
    "🇨🇷": "Costa Rica",
    "CR":  "Costa Rica",
    "🇨🇺": "Cuba",
    "CU":  "Cuba",
    "🇨🇼": "Curacao",
    "CW":  "Curacao",
    "🇩🇴": "Dominican Republic",
    "DO":  "Dominican Republic",
    "🇸🇻": "El Salvador",
    "SV":  "El Salvador",
    "🇬🇹": "Guatemala",
    "GT":  "Guatemala",
    "🇭🇹": "Haiti",
    "HT":  "Haiti",
    "🇭🇳": "Honduras",
    "HN":  "Honduras",
    "🇯🇲": "Jamaica",
    "JM":  "Jamaica",
    "🇲🇽": "Mexico",
    "MX":  "Mexico",
    "🇳🇮": "Nicaragua",
    "NI":  "Nicaragua",
    "🇵🇦": "Panama",
    "PA":  "Panama",
    "🇹🇹": "Trinidad and Tobago",
    "TT":  "Trinidad and Tobago",
    "🇺🇸": "USA",
    "US":  "USA",
    "🇬🇾": "Guyana",
    "GY":  "Guyana",
    "🇧🇧": "Barbados",
    "BB":  "Barbados",
    "🇬🇩": "Grenada",
    "GD":  "Grenada",
    "🇸🇷": "Suriname",
    "SR":  "Suriname",
    # ── AFC (Asia) ────────────────────────────────────────────────────────────
    "🇦🇫": "Afghanistan",
    "AF":  "Afghanistan",
    "🇧🇭": "Bahrain",
    "BH":  "Bahrain",
    "🇧🇩": "Bangladesh",
    "BD":  "Bangladesh",
    "🇧🇳": "Brunei",
    "BN":  "Brunei",
    "🇨🇳": "China",
    "CN":  "China",
    "🇭🇰": "Hong Kong",
    "HK":  "Hong Kong",
    "🇮🇳": "India",
    "IN":  "India",
    "🇮🇩": "Indonesia",
    "ID":  "Indonesia",
    "🇮🇷": "Iran",
    "IR":  "Iran",
    "🇮🇶": "Iraq",
    "IQ":  "Iraq",
    "🇮🇱": "Israel",
    "IL":  "Israel",
    "🇯🇵": "Japan",
    "JP":  "Japan",
    "🇯🇴": "Jordan",
    "JO":  "Jordan",
    "🇰🇿": "Kazakhstan",
    "KZ":  "Kazakhstan",
    "🇰🇼": "Kuwait",
    "KW":  "Kuwait",
    "🇰🇬": "Kyrgyzstan",
    "KG":  "Kyrgyzstan",
    "🇱🇦": "Laos",
    "LA":  "Laos",
    "🇱🇧": "Lebanon",
    "LB":  "Lebanon",
    "🇲🇾": "Malaysia",
    "MY":  "Malaysia",
    "🇲🇻": "Maldives",
    "MV":  "Maldives",
    "🇲🇳": "Mongolia",
    "MN":  "Mongolia",
    "🇲🇲": "Myanmar",
    "MM":  "Myanmar",
    "🇳🇵": "Nepal",
    "NP":  "Nepal",
    "🇰🇵": "North Korea",
    "KP":  "North Korea",
    "🇴🇲": "Oman",
    "OM":  "Oman",
    "🇵🇰": "Pakistan",
    "PK":  "Pakistan",
    "🇵🇸": "Palestine",
    "PS":  "Palestine",
    "🇵🇭": "Philippines",
    "PH":  "Philippines",
    "🇶🇦": "Qatar",
    "QA":  "Qatar",
    "🇸🇦": "Saudi Arabia",
    "SA":  "Saudi Arabia",
    "🇸🇬": "Singapore",
    "SG":  "Singapore",
    "🇰🇷": "South Korea",
    "KR":  "South Korea",
    "🇱🇰": "Sri Lanka",
    "LK":  "Sri Lanka",
    "🇸🇾": "Syria",
    "SY":  "Syria",
    "🇹🇼": "Taiwan",
    "TW":  "Taiwan",
    "🇹🇯": "Tajikistan",
    "TJ":  "Tajikistan",
    "🇹🇭": "Thailand",
    "TH":  "Thailand",
    "🇹🇱": "Timor-Leste",
    "TL":  "Timor-Leste",
    "🇹🇲": "Turkmenistan",
    "TM":  "Turkmenistan",
    "🇦🇪": "United Arab Emirates",
    "AE":  "United Arab Emirates",
    "🇺🇿": "Uzbekistan",
    "UZ":  "Uzbekistan",
    "🇻🇳": "Vietnam",
    "VN":  "Vietnam",
    "🇾🇪": "Yemen",
    "YE":  "Yemen",
    # ── CAF (Africa) ──────────────────────────────────────────────────────────
    "🇩🇿": "Algeria",
    "DZ":  "Algeria",
    "🇦🇴": "Angola",
    "AO":  "Angola",
    "🇧🇯": "Benin",
    "BJ":  "Benin",
    "🇧🇼": "Botswana",
    "BW":  "Botswana",
    "🇧🇫": "Burkina Faso",
    "BF":  "Burkina Faso",
    "🇧🇮": "Burundi",
    "BI":  "Burundi",
    "🇨🇲": "Cameroon",
    "CM":  "Cameroon",
    "🇨🇻": "Cape Verde",
    "CV":  "Cape Verde",
    "🇨🇫": "Central African Republic",
    "CF":  "Central African Republic",
    "🇹🇩": "Chad",
    "TD":  "Chad",
    "🇰🇲": "Comoros",
    "KM":  "Comoros",
    "🇨🇩": "DR Congo",
    "CD":  "DR Congo",
    "🇨🇬": "Republic of Congo",
    "CG":  "Republic of Congo",
    "🇨🇮": "Ivory Coast",
    "CI":  "Ivory Coast",
    "🇩🇯": "Djibouti",
    "DJ":  "Djibouti",
    "🇪🇬": "Egypt",
    "EG":  "Egypt",
    "🇬🇶": "Equatorial Guinea",
    "GQ":  "Equatorial Guinea",
    "🇪🇷": "Eritrea",
    "ER":  "Eritrea",
    "🇸🇿": "Eswatini",
    "SZ":  "Eswatini",
    "🇪🇹": "Ethiopia",
    "ET":  "Ethiopia",
    "🇬🇦": "Gabon",
    "GA":  "Gabon",
    "🇬🇲": "Gambia",
    "GM":  "Gambia",
    "🇬🇭": "Ghana",
    "GH":  "Ghana",
    "🇬🇳": "Guinea",
    "GN":  "Guinea",
    "🇬🇼": "Guinea-Bissau",
    "GW":  "Guinea-Bissau",
    "🇰🇪": "Kenya",
    "KE":  "Kenya",
    "🇱🇸": "Lesotho",
    "LS":  "Lesotho",
    "🇱🇷": "Liberia",
    "LR":  "Liberia",
    "🇱🇾": "Libya",
    "LY":  "Libya",
    "🇲🇬": "Madagascar",
    "MG":  "Madagascar",
    "🇲🇼": "Malawi",
    "MW":  "Malawi",
    "🇲🇱": "Mali",
    "ML":  "Mali",
    "🇲🇷": "Mauritania",
    "MR":  "Mauritania",
    "🇲🇺": "Mauritius",
    "MU":  "Mauritius",
    "🇲🇦": "Morocco",
    "MA":  "Morocco",
    "🇲🇿": "Mozambique",
    "MZ":  "Mozambique",
    "🇳🇦": "Namibia",
    "NA":  "Namibia",
    "🇳🇪": "Niger",
    "NE":  "Niger",
    "🇳🇬": "Nigeria",
    "NG":  "Nigeria",
    "🇷🇼": "Rwanda",
    "RW":  "Rwanda",
    "🇸🇹": "São Tomé and Príncipe",
    "ST":  "São Tomé and Príncipe",
    "🇸🇳": "Senegal",
    "SN":  "Senegal",
    "🇸🇨": "Seychelles",
    "SC":  "Seychelles",
    "🇸🇱": "Sierra Leone",
    "SL":  "Sierra Leone",
    "🇸🇴": "Somalia",
    "SO":  "Somalia",
    "🇿🇦": "South Africa",
    "ZA":  "South Africa",
    "🇸🇸": "South Sudan",
    "SS":  "South Sudan",
    "🇸🇩": "Sudan",
    "SD":  "Sudan",
    "🇹🇿": "Tanzania",
    "TZ":  "Tanzania",
    "🇹🇬": "Togo",
    "TG":  "Togo",
    "🇹🇳": "Tunisia",
    "TN":  "Tunisia",
    "🇺🇬": "Uganda",
    "UG":  "Uganda",
    "🇿🇲": "Zambia",
    "ZM":  "Zambia",
    "🇿🇼": "Zimbabwe",
    "ZW":  "Zimbabwe",
    # ── OFC (Oceania) ─────────────────────────────────────────────────────────
    "🇦🇺": "Australia",
    "AU":  "Australia",
    "🇫🇯": "Fiji",
    "FJ":  "Fiji",
    "🇳🇿": "New Zealand",
    "NZ":  "New Zealand",
    "🇵🇬": "Papua New Guinea",
    "PG":  "Papua New Guinea",
    "🇸🇧": "Solomon Islands",
    "SB":  "Solomon Islands",
    "🇹🇴": "Tonga",
    "TO":  "Tonga",
    "🇻🇺": "Vanuatu",
    "VU":  "Vanuatu",
    "🇼🇸": "Samoa",
    "WS":  "Samoa",
    # ── Misc already in use ───────────────────────────────────────────────────
    "🇮🇲": "Isle of Man",
    "IM":  "Isle of Man",
    "🇧🇹": "Bhutan",
    "BT":  "Bhutan",
}
